import { HardAndSoftSkillsArray } from '../helpers/mainDbIteration';

export const seniorFrontEndSkills: HardAndSoftSkillsArray = [
    { mainName: 'typescript', count: 0, subNames: ['TypeScript', 'typescript', 'typescript.js', 'type script'] },
    { mainName: 'html', count: 0, subNames: ['html', 'html5', 'Semantic HTML'] },
    { mainName: 'css', count: 0, subNames: ['css', 'css3'] },
    { mainName: 'react', count: 0, subNames: ['react', 'react.js', 'reactjs', 'react js'] },
    { mainName: 'angular', count: 0, subNames: ['angular', 'angular.js', 'angularjs', 'angular js'] },
    { mainName: 'vue', count: 0, subNames: ['vue', 'vue.js', 'vuejs', 'vue js', 'Vue 3'] },
    { mainName: 'node.js', count: 0, subNames: ['node.js', 'nodejs', 'node js', 'node'] },
    { mainName: 'react class components', count: 0, subNames: ['react class components', 'react class component'] },
    {
        mainName: 'react functional components',
        count: 0,
        subNames: ['react functional components', 'react functional component']
    },
    { mainName: 'react hooks', count: 0, subNames: ['react hooks', 'react hook', 'Hooks'] },
    { mainName: 'redux', count: 0, subNames: ['redux', 'Redux.js', 'Redux Toolkit'] },
    {
        mainName: 'state management tools',
        count: 0,
        subNames: [
            'state management tools',
            'state management tool',
            'State management',
            'State management for loading/skeleton/error',
            'State management systems',
            'State management libraries',
            'State management patterns'
        ]
    },
    {
        mainName: 'SaaS experience',
        count: 0,
        subNames: ['SaaS experience', 'saas experience', 'saas product development']
    },
    { mainName: 'cloud platforms', count: 0, subNames: ['cloud platforms', 'Cloud services'] },
    { mainName: 'pixel-perfect', count: 0, subNames: ['pixel-perfect ui implementation', 'pixel-perfect ui'] },
    { mainName: 'subscription management', count: 0, subNames: ['subscription management'] },
    { mainName: 'access auditing', count: 0, subNames: ['access auditing'] },
    { mainName: 'fintech knowledge', count: 0, subNames: ['fintech knowledge'] },
    {
        mainName: 'javascript',
        count: 0,
        subNames: ['javascript', 'JavaScript (ES6+)', 'JavaScript/ES6+', 'modern JavaScript']
    },
    { mainName: 'next.js', count: 0, subNames: ['next.js'] },
    { mainName: 'rest api', count: 0, subNames: ['rest apis', 'rest api', 'RESTful APIs', 'RESTful Services'] },
    {
        mainName: 'responsive design',
        count: 0,
        subNames: ['responsive design', 'Responsive layout', 'Responsive web design']
    },
    {
        mainName: 'mobile first',
        count: 0,
        subNames: ['mobile-first development', 'mobile first development', 'mobile first']
    },
    { mainName: 'jest', count: 0, subNames: ['jest'] },
    { mainName: 'cypress', count: 0, subNames: ['cypress'] },
    { mainName: 'webpack', count: 0, subNames: ['webpack'] },
    { mainName: 'babel', count: 0, subNames: ['babel'] },
    { mainName: 'graphql', count: 0, subNames: ['graphql'] },
    { mainName: 'docker', count: 0, subNames: ['docker'] },
    { mainName: 'kubernetes', count: 0, subNames: ['kubernetes', 'Kubernetes deployment'] },
    {
        mainName: 'ci/cd',
        count: 0,
        subNames: ['ci/cd', 'continuous integration', 'continuous deployment', 'CI/CD pipelines', 'CI/CD practices']
    },
    {
        mainName: 'agile',
        count: 0,
        subNames: [
            'agile methodologies',
            'agile methodology',
            'agile development',
            'scrum',
            'agile / scrum',
            'Agile workflow',
            'agile teamwork',
            'Agile Project Management tools',
            'Agile'
        ]
    },
    { mainName: 'playwright', count: 0, subNames: ['playwright'] },
    { mainName: 'github copilot', count: 0, subNames: ['github copilot'] },
    { mainName: 'claude code', count: 0, subNames: ['claude code'] },
    { mainName: 'cursor', count: 0, subNames: ['cursor'] },
    {
        mainName: 'web performance',
        count: 0,
        subNames: [
            'web performance',
            'performance optimization',
            'Performance tooling',
            'webpagetest',
            'Web performance optimization',
            'Frontend performance optimization',
            'Performance optimisation',
            'Runtime performance optimization',
            'runtime performance',
            'Performance audits',
            'Performance profiling'
        ]
    },
    { mainName: 'styled components', count: 0, subNames: ['styled components'] },
    { mainName: 'storybook', count: 0, subNames: ['storybook'] },
    { mainName: 'monorepos', count: 0, subNames: ['monorepos'] },
    {
        mainName: 'design systems',
        count: 0,
        subNames: ['design systems', 'design system', 'Scalable system design', 'Fault-tolerant system design']
    },
    { mainName: 'accessibility', count: 0, subNames: ['accessibility', 'WCAG accessibility', 'Accessibility (WCAG)'] },
    { mainName: 'design patterns', count: 0, subNames: ['design patterns'] },
    { mainName: 'testing', count: 0, subNames: ['testing', 'Testable code'] },
    {
        mainName: 'frontend architecture',
        count: 0,
        subNames: ['frontend architecture', 'client-side architecture', 'Software architecture']
    },
    { mainName: 'git', count: 0, subNames: ['git'] },
    { mainName: 'jira', count: 0, subNames: ['jira'] },
    { mainName: 'confluence', count: 0, subNames: ['confluence'] },
    {
        mainName: 'ui/ux',
        count: 0,
        subNames: [
            'ui/ux',
            'UX best practices',
            'UI/UX design',
            'UX understanding',
            'UI/UX implementation',
            'UI/UX best practices',
            'UI & UX design',
            'Design principles',
            'UX process',
            'UI/UX development',
            'UX design translation to UI'
        ]
    },
    { mainName: 'no designer', count: 0, subNames: ['no designer', 'ui/ux design without ux support'] },
    { mainName: 'data-heavy interfaces', count: 0, subNames: ['data-heavy interfaces'] },
    { mainName: 'flutterflow', count: 0, subNames: ['flutterflow'] },
    { mainName: 'streamlit', count: 0, subNames: ['streamlit'] },
    { mainName: 'svelte', count: 0, subNames: ['svelte', 'sveltekit'] },
    {
        mainName: 'component libraries',
        count: 0,
        subNames: ['component libraries', 'component library', 'Component library management']
    },
    { mainName: 'theming', count: 0, subNames: ['tokens and theming', 'tokens', 'theming'] },
    { mainName: 'figma', count: 0, subNames: ['figma', 'Figma to production UI'] },
    { mainName: 'animations', count: 0, subNames: ['animations'] },
    { mainName: 'micro-interactions', count: 0, subNames: ['micro-interactions'] },
    { mainName: 'framer motion', count: 0, subNames: ['framer motion'] },
    { mainName: 'gsap', count: 0, subNames: ['gsap'] },
    { mainName: 'aria', count: 0, subNames: ['aria'] },
    { mainName: 'keyboard support', count: 0, subNames: ['keyboard support'] },
    { mainName: 'color contrast standards', count: 0, subNames: ['color contrast standards'] },
    { mainName: 'container queries', count: 0, subNames: ['container queries'] },
    { mainName: 'css grid', count: 0, subNames: ['css grid'] },
    { mainName: 'flexbox', count: 0, subNames: ['flexbox'] },
    { mainName: 'css custom properties', count: 0, subNames: ['css custom properties'] },
    { mainName: 'tailwind', count: 0, subNames: ['tailwind css', 'tailwind'] },
    { mainName: 'shadcn/ui', count: 0, subNames: ['shadcn/ui'] },
    { mainName: 'bundle size optimization', count: 0, subNames: ['bundle size optimization'] },
    { mainName: 'code splitting', count: 0, subNames: ['code splitting'] },
    { mainName: 'hydration strategies', count: 0, subNames: ['hydration strategies'] },
    { mainName: 'caching strategies', count: 0, subNames: ['caching strategies'] },
    { mainName: 'virtualization', count: 0, subNames: ['virtualization'] },
    { mainName: 'react query', count: 0, subNames: ['react query'] },
    { mainName: 'lazy loading', count: 0, subNames: ['lazy loading'] },
    { mainName: 'swr', count: 0, subNames: ['swr'] },
    { mainName: 'digital wallets', count: 0, subNames: ['wallet integrations', 'WalletConnect'] },
    { mainName: 'injected providers', count: 0, subNames: ['injected providers'] },
    { mainName: 'on-chain data rendering', count: 0, subNames: ['on-chain data rendering'] },
    { mainName: 'rpc/indexer integration', count: 0, subNames: ['rpc/indexer integration'] },
    { mainName: 'testing best practices', count: 0, subNames: ['testing best practices'] },
    { mainName: 'ci checks', count: 0, subNames: ['ci checks'] },
    { mainName: 'documentation', count: 0, subNames: ['documentation', 'Technical documentation'] },
    { mainName: 'ui refactoring', count: 0, subNames: ['ui refactoring'] },
    { mainName: 'testing library', count: 0, subNames: ['testing library'] },
    { mainName: 'chromatic', count: 0, subNames: ['chromatic'] },
    { mainName: 'visual regression testing', count: 0, subNames: ['visual regression testing'] },
    { mainName: 'style dictionary', count: 0, subNames: ['style dictionary'] },
    { mainName: 'lighthouse', count: 0, subNames: ['lighthouse'] },
    { mainName: 'perfetto', count: 0, subNames: ['perfetto'] },
    { mainName: 'sentry', count: 0, subNames: ['sentry'] },
    { mainName: 'datadog', count: 0, subNames: ['datadog'] },
    { mainName: 'new relic', count: 0, subNames: ['new relic'] },
    { mainName: 'i18n', count: 0, subNames: ['i18n'] },
    { mainName: 'rtl support', count: 0, subNames: ['rtl support'] },
    { mainName: 'webgl', count: 0, subNames: ['webgl'] },
    { mainName: 'canvas', count: 0, subNames: ['canvas'] },
    { mainName: 'svg', count: 0, subNames: ['svg'] },
    { mainName: 'monitoring tools', count: 0, subNames: ['monitoring tools', 'System performance monitoring'] },
    { mainName: 'mobx', count: 0, subNames: ['mobx'] },
    { mainName: 'less', count: 0, subNames: ['less'] },
    { mainName: 'sass', count: 0, subNames: ['sass'] },
    { mainName: 'relational databases', count: 0, subNames: ['relational databases'] },
    { mainName: 'nosql databases', count: 0, subNames: ['nosql databases'] },
    { mainName: 'aws', count: 0, subNames: ['aws', 'AWS cloud services', 'AWS/cloud technologies', 'AWS hosting'] },
    { mainName: 'linux', count: 0, subNames: ['linux'] },
    { mainName: 'vite', count: 0, subNames: ['vite'], meta: 'Webpack clone' },
    { mainName: 'xstate', count: 0, subNames: ['xstate'] },
    { mainName: 'wagmi', count: 0, subNames: ['wagmi'] },
    { mainName: 'react native', count: 0, subNames: ['react native'] },
    { mainName: 'frontend optimization', count: 0, subNames: ['frontend optimization'] },
    { mainName: 'sdk development', count: 0, subNames: ['sdk development'] },
    { mainName: 'cross-chain dapps', count: 0, subNames: ['cross-chain dapps'] },
    { mainName: 'blockchain technology', count: 0, subNames: ['blockchain technology'] },
    { mainName: 'defi platforms', count: 0, subNames: ['defi platforms'] },
    { mainName: 'observability and tracing', count: 0, subNames: ['observability and tracing'] },
    { mainName: 'state machines', count: 0, subNames: ['state machines'] },
    {
        mainName: 'mobile, tablet, and desktop frontend development',
        count: 0,
        subNames: ['mobile, tablet, and desktop frontend development']
    },
    { mainName: 'code quality', count: 0, subNames: ['code quality'] },
    { mainName: 'code maintainability', count: 0, subNames: ['code maintainability', 'Maintainable code'] },
    { mainName: 'css-in-js', count: 0, subNames: ['css-in-js'] },
    { mainName: 'zustand', count: 0, subNames: ['zustand'] },
    { mainName: 'recoil', count: 0, subNames: ['recoil'] },
    { mainName: 'asynchronous operations', count: 0, subNames: ['asynchronous operations'] },
    {
        mainName: 'frontend-backend integration',
        count: 0,
        subNames: ['frontend-backend integration', 'Backend integration']
    },
    { mainName: 'unit testing', count: 0, subNames: ['unit testing'] },
    { mainName: 'integration testing', count: 0, subNames: ['integration testing'] },
    {
        mainName: 'react testing library',
        count: 0,
        subNames: ['react testing library', 'Component/integration testing (React Testing Library)']
    },
    { mainName: 'grpc', count: 0, subNames: ['grpc'] },
    { mainName: 'backend technologies', count: 0, subNames: ['backend technologies'] },
    { mainName: 'backend databases', count: 0, subNames: ['backend databases'] },
    {
        mainName: 'reusable components',
        count: 0,
        subNames: [
            'modular component design',
            'Frontend component-based architecture',
            'component-based architecture',
            'reusable components',
            'Reusable UI components',
            'component based architecture',
            'Reusable code',
            'modular code',
            'Reusable code design'
        ]
    },
    { mainName: 'localization', count: 0, subNames: ['localization'] },
    {
        mainName: 'build tools',
        count: 0,
        subNames: [
            'build tooling',
            'Front-end build tools',
            'build tooling',
            'Frontend build tools',
            'Modern build tools',
            'Modern front-end build pipelines',
            'build tools'
        ],
        meta: 'this refers to WebPack... e.g. of post in Amazon AWS -> Modern build tools (Webpack, Vite, or similar)'
    },
    { mainName: 'observability', count: 0, subNames: ['observability'] },
    { mainName: 'code review', count: 0, subNames: ['code review', 'code reviews'] },
    { mainName: 'design documentation', count: 0, subNames: ['design documentation'] },
    {
        mainName: 'technical mentoring',
        count: 0,
        subNames: ['technical mentoring', 'Technical leadership', 'Code mentorship']
    },
    { mainName: 'reliability best practices', count: 0, subNames: ['reliability best practices'] },
    { mainName: 'test-driven development', count: 0, subNames: ['test-driven development'] },
    {
        mainName: 'object-oriented programming',
        count: 0,
        subNames: ['object-oriented programming', 'Object-Oriented Programming (OOP)', 'OOP', 'OO languages']
    },
    { mainName: 'solid principles', count: 0, subNames: ['solid principles'] },
    { mainName: 'dry principles', count: 0, subNames: ['dry principles'] },
    { mainName: 'software design principles', count: 0, subNames: ['software design principles'] },
    {
        mainName: 'software development life cycle',
        count: 0,
        subNames: [
            'software development life cycle (sdlc)',
            'software development life cycle',
            'sdlc',
            'Web development lifecycle'
        ]
    },
    { mainName: 'c++', count: 0, subNames: ['c++'] },
    { mainName: 'c#', count: 0, subNames: ['c#'] },
    { mainName: '.net', count: 0, subNames: ['.net'] },
    { mainName: 'azure devops', count: 0, subNames: ['azure devops'] },
    { mainName: 'backlog management', count: 0, subNames: ['backlog management'] },
    { mainName: 'team foundation server', count: 0, subNames: ['team foundation server', 'tfs'] },
    { mainName: 'activex data objects', count: 0, subNames: ['activex data objects', 'ado'] },
    { mainName: 'software design diagrams', count: 0, subNames: ['software design diagrams'] },
    {
        mainName: 'mathematical foundations',
        count: 0,
        subNames: ['mathematical foundations (geometry, trigonometry)', 'geometry', 'trigonometry']
    },
    { mainName: 'infrastructure software knowledge', count: 0, subNames: ['infrastructure software knowledge'] },
    { mainName: 'react context', count: 0, subNames: ['react context'] },
    { mainName: 'react suspense', count: 0, subNames: ['react suspense'] },
    { mainName: 'concurrent react features', count: 0, subNames: ['concurrent react features'] },
    { mainName: 'tanstack query', count: 0, subNames: ['tanstack query'] },
    { mainName: 'graphql', count: 0, subNames: ['graphql', 'GraphQL (queries, mutations, caching, fragments)'] },
    { mainName: 'vitest', count: 0, subNames: ['vitest'] },
    { mainName: 'component testing', count: 0, subNames: ['component testing'] },
    { mainName: 'e2e testing', count: 0, subNames: ['e2e testing', 'End-to-end testing'] },
    { mainName: 'modern frontend patterns', count: 0, subNames: ['modern frontend patterns'] },
    {
        mainName: 'maintainable architecture',
        count: 0,
        subNames: ['maintainable architecture', 'Maintainable system design']
    },
    { mainName: 'internationalization', count: 0, subNames: ['internationalization'] },
    { mainName: 'translation workflows', count: 0, subNames: ['translation workflows'] },
    { mainName: 'collaboration with designers', count: 0, subNames: ['collaboration with designers'] },
    { mainName: 'collaboration with product managers', count: 0, subNames: ['collaboration with product managers'] },
    { mainName: 'react router', count: 0, subNames: ['react routing', 'react router'] },
    { mainName: 'component composition', count: 0, subNames: ['component composition'] },
    {
        mainName: 'mui',
        count: 0,
        subNames: ['mui', 'Material UI', 'Material UI (MUI)', 'Material Design', 'Material-UI']
    },
    { mainName: 'spa development', count: 0, subNames: ['spa development', 'single page application'] },
    { mainName: 'object-oriented javascript', count: 0, subNames: ['object-oriented javascript'] },
    { mainName: 'ui testing', count: 0, subNames: ['ui testing'] },
    { mainName: 'selenium', count: 0, subNames: ['selenium'] },
    {
        mainName: 'front-end tooling',
        count: 0,
        subNames: ['front-end tooling', 'Modern front-end tooling', 'Developer tooling']
    },
    { mainName: 'eslint', count: 0, subNames: ['eslint'] },
    { mainName: 'prettier', count: 0, subNames: ['prettier'] },
    { mainName: 'micro frontend applications', count: 0, subNames: ['micro frontend applications'] },
    {
        mainName: 'angular 2',
        count: 0,
        subNames: ['angular 2', 'angular 2+', 'Angular 15', 'Angular (13+)', 'Angular 20', 'Angular (v8+)']
    },
    {
        mainName: 'web development',
        count: 0,
        subNames: ['web development', 'Frontend development', 'Frontend web development', 'Web client development']
    },
    {
        mainName: 'testing frameworks',
        count: 0,
        subNames: ['testing frameworks', 'Frontend testing frameworks', 'test runner frameworks']
    },
    { mainName: 'grasp principles', count: 0, subNames: ['grasp principles'] },
    { mainName: 'cross-browser compatibility', count: 0, subNames: ['cross-browser compatibility'] },
    { mainName: 'npm', count: 0, subNames: ['npm', 'node package manager'] },
    { mainName: 'linters', count: 0, subNames: ['linters'] },
    { mainName: 'nx framework', count: 0, subNames: ['nx framework', 'Nx'] },
    { mainName: 'typescript ast', count: 0, subNames: ['typescript ast', 'typescript abstract syntax tree'] },
    { mainName: 'code modifiers', count: 0, subNames: ['code modifiers'] },
    { mainName: 'gitlab', count: 0, subNames: ['gitlab'] },
    { mainName: 'nginx', count: 0, subNames: ['nginx'] },
    { mainName: 'modern frameworks', count: 0, subNames: ['modern frameworks'] },
    { mainName: 'api development', count: 0, subNames: ['api development', 'API design'] },
    { mainName: 'backend api layer experience', count: 0, subNames: ['backend api layer experience'] },
    { mainName: 'sql', count: 0, subNames: ['sql', 'SQL querying tools'] },
    { mainName: 'data-driven query languages', count: 0, subNames: ['data-driven query languages'] },
    { mainName: 'cloud services ui development', count: 0, subNames: ['cloud services ui development'] },
    { mainName: 'golang', count: 0, subNames: ['golang'] },
    { mainName: 'postgresql', count: 0, subNames: ['postgresql', 'Postgres', 'Postgres (context)'] },
    { mainName: 'data visualization', count: 0, subNames: ['data visualization'] },
    { mainName: 'ai-powered solutions', count: 0, subNames: ['ai-powered solutions'] },
    { mainName: 'chatbots', count: 0, subNames: ['chatbots'] },
    { mainName: 'llm workflows', count: 0, subNames: ['llm workflows'] },
    { mainName: 'openai gpt', count: 0, subNames: ['openai gpt'] },
    { mainName: 'ssr', count: 0, subNames: ['ssr', 'server side rendering', 'server-side rendering'] },
    { mainName: 'ssg', count: 0, subNames: ['ssg'] },
    { mainName: 'dashboards', count: 0, subNames: ['dashboards'] },
    { mainName: 'ally', count: 0, subNames: ['ally'], meta: 'this is Accessibility tool for Wordpress' },
    { mainName: 'wordpress', count: 0, subNames: ['wordpress'] },
    { mainName: 'joomla', count: 0, subNames: ['joomla'] },
    { mainName: 'drupal', count: 0, subNames: ['drupal'] },
    { mainName: 'cockpit', count: 0, subNames: ['cockpit cms', 'cockpit'], meta: 'its a content management system' },
    {
        mainName: 'core web vitals optimization',
        count: 0,
        subNames: ['core web vitals optimization', 'Core Web Vitals']
    },
    { mainName: 'routing', count: 0, subNames: ['routing'] },
    { mainName: 'modularization', count: 0, subNames: ['modularization'] },
    { mainName: 'legacy code refactoring', count: 0, subNames: ['legacy code refactoring'] },
    { mainName: 'architectural improvements', count: 0, subNames: ['architectural improvements'] },
    { mainName: 'api collaboration', count: 0, subNames: ['api collaboration'] },
    { mainName: 'large-scale applications', count: 0, subNames: ['large-scale applications'] },
    { mainName: 'jasmine', count: 0, subNames: ['jasmine'] },
    { mainName: 'karma', count: 0, subNames: ['karma'] },
    { mainName: 'version control', count: 0, subNames: ['version control'] },
    { mainName: 'refactoring', count: 0, subNames: ['refactoring'] },
    { mainName: 'shadcn ui components', count: 0, subNames: ['shadcn ui components'] },
    { mainName: 'tanstack router', count: 0, subNames: ['tanstack router'] },
    { mainName: 'tanstack libraries', count: 0, subNames: ['tanstack libraries'] },
    { mainName: 'github', count: 0, subNames: ['github', 'GitHub Actions'] },
    {
        mainName: 'containerized application development',
        count: 0,
        subNames: ['containerized application development', 'Containerized environments']
    },
    {
        mainName: 'automation testing',
        count: 0,
        subNames: ['automation testing', 'Automated testing', 'Browser testing']
    },
    { mainName: 'ngrx', count: 0, subNames: ['ngrx'] },
    { mainName: 'rxjs', count: 0, subNames: ['rxjs'] },
    { mainName: 'cloud technologies', count: 0, subNames: ['cloud technologies'] },
    { mainName: 'mysql', count: 0, subNames: ['mysql'] },
    {
        mainName: 'seo best practices',
        count: 0,
        subNames: [
            'seo',
            'search-engine-optimization',
            'seo-best-practices',
            'seo best practices',
            'search engine optimization',
            'SEO compliance',
            'SEO optimization'
        ]
    },
    {
        mainName: 'Third-party APIs',
        count: 0,
        subNames: ['Third-party APIs', 'third-party services', 'Integration of third-party services']
    },
    { mainName: 'Analytics integrations', count: 0, subNames: ['Analytics integrations'] },
    { mainName: 'CMS integrations', count: 0, subNames: ['CMS integrations', 'Headless CMS integrations', 'CMS'] },
    { mainName: 'Elixir/Phoenix (context)', count: 0, subNames: ['Elixir/Phoenix (context)'] },
    { mainName: 'Express.js', count: 0, subNames: ['Express.js'] },
    { mainName: 'Ant Design', count: 0, subNames: ['Ant Design'] },
    { mainName: 'MongoDb', count: 0, subNames: ['MongoDb'] },
    { mainName: 'DynamoDb', count: 0, subNames: ['DynamoDb'] },
    {
        mainName: 'Database schema design',
        count: 0,
        subNames: ['Database schema design', 'schema design', 'Database design']
    },
    { mainName: 'Database performance optimization', count: 0, subNames: ['Database performance optimization'] },
    { mainName: 'GCP', count: 0, subNames: ['GCP'] },
    { mainName: 'Azure', count: 0, subNames: ['Azure'] },
    { mainName: 'Containerization', count: 0, subNames: ['Containerization'] },
    { mainName: 'Scalable backend systems', count: 0, subNames: ['Scalable backend systems'] },
    {
        mainName: 'Fullstack web application development',
        count: 0,
        subNames: [
            'Fullstack web application development',
            'Fullstack development',
            'Frontend and backend tooling setup'
        ]
    },
    {
        mainName: 'Software development',
        count: 0,
        subNames: ['Software development', 'Software development processes']
    },
    { mainName: 'Web applications', count: 0, subNames: ['Web applications'] },
    { mainName: 'Security', count: 0, subNames: ['Security', 'Secure coding practices', 'Secure web application development'] },
    { mainName: 'WebSockets', count: 0, subNames: ['WebSockets', 'Web Sockets'] },
    {
        mainName: 'Experience in large technology organizations',
        count: 0,
        subNames: ['Experience in large technology organizations']
    },
    {
        mainName: 'fast growing startups',
        count: 0,
        subNames: ['fast growing startups', 'Experience in fast growing startups']
    },
    { mainName: 'Consumer payments experience', count: 0, subNames: ['Consumer payments experience'] },
    { mainName: 'Crypto applications experience', count: 0, subNames: ['Crypto applications experience'] },
    {
        mainName: 'Fintech mobile applications experience',
        count: 0,
        subNames: ['Fintech mobile applications experience']
    },
    { mainName: 'Async/Await', count: 0, subNames: ['Async/Await'] },
    { mainName: 'Clean code', count: 0, subNames: ['Clean code'] },
    { mainName: 'Well-documented code', count: 0, subNames: ['Well-documented code'] },
    { mainName: 'Ember', count: 0, subNames: ['Ember'] },
    { mainName: 'AJAX', count: 0, subNames: ['AJAX'] },
    { mainName: 'Atomic CSS', count: 0, subNames: ['Atomic CSS', 'Atomic design'] },
    { mainName: 'Superagent', count: 0, subNames: ['Superagent'] },
    { mainName: 'Web Vitals', count: 0, subNames: ['Web Vitals'] },
    { mainName: 'JSON', count: 0, subNames: ['JSON'] },
    { mainName: 'WebdriverIO', count: 0, subNames: ['WebdriverIO'] },
    { mainName: 'Mock Service Worker', count: 0, subNames: ['Mock Service Worker'] },
    { mainName: 'Application stability', count: 0, subNames: ['Application stability'] },
    {
        mainName: 'Debugging',
        count: 0,
        subNames: ['Debugging large-scale web applications', 'Debugging']
    },
    {
        mainName: 'Figma to pixel-perfect implementation',
        count: 0,
        subNames: ['Figma to pixel-perfect implementation']
    },
    { mainName: 'iOS development', count: 0, subNames: ['iOS development'] },
    { mainName: 'Android development', count: 0, subNames: ['Android development'] },
    { mainName: 'Multi-channel deployment', count: 0, subNames: ['Multi-channel deployment'] },
    { mainName: 'MFA implementation', count: 0, subNames: ['MFA implementation'] },
    { mainName: 'SSO', count: 0, subNames: ['SSO'] },
    { mainName: 'Offline-first applications', count: 0, subNames: ['Offline-first applications'] },
    { mainName: 'Local storage', count: 0, subNames: ['Local storage'] },
    { mainName: 'Deep linking', count: 0, subNames: ['Deep linking'] },
    { mainName: 'Notifications', count: 0, subNames: ['Notifications'] },
    { mainName: 'UI code deployment', count: 0, subNames: ['UI code deployment'] },
    { mainName: 'Release management', count: 0, subNames: ['Release management'] },
    { mainName: 'User behavior tracking', count: 0, subNames: ['User behavior tracking'] },
    { mainName: 'Alerting principles', count: 0, subNames: ['Alerting principles'] },
    {
        mainName: 'DevOps/SRE automation for UI deployments',
        count: 0,
        subNames: ['DevOps/SRE automation for UI deployments']
    },
    { mainName: 'AI tooling', count: 0, subNames: ['AI tooling'] },
    { mainName: 'Visual design', count: 0, subNames: ['Visual design'] },
    { mainName: 'Cross-channel UI frameworks', count: 0, subNames: ['Cross-channel UI frameworks'] },
    { mainName: 'jQuery', count: 0, subNames: ['jQuery'] },
    { mainName: 'MERN stack', count: 0, subNames: ['MERN stack'] },
    { mainName: 'Query optimization', count: 0, subNames: ['Query optimization'] },
    { mainName: 'Frontend migrations', count: 0, subNames: ['Frontend migrations'] },
    { mainName: 'Greenfield development', count: 0, subNames: ['Greenfield development'] },
    { mainName: 'Python', count: 0, subNames: ['Python'] },
    { mainName: 'Spark', count: 0, subNames: ['Spark'] },
    { mainName: 'Snowflake', count: 0, subNames: ['Snowflake'] },
    {
        mainName: 'PWA',
        count: 0,
        subNames: ['PWA', 'PWA development'],
        meta: 'progressive web application, this is like Single page application, just another term for it'
    },
    { mainName: 'Web Workers', count: 0, subNames: ['Web Workers'] },
    { mainName: 'CQRS', count: 0, subNames: ['CQRS'] },
    { mainName: 'DevOps', count: 0, subNames: ['DevOps'] },
    { mainName: 'SecDevOps', count: 0, subNames: ['SecDevOps'] },
    { mainName: 'Efficient data handling', count: 0, subNames: ['Efficient data handling'] },
    { mainName: 'Vue Composition API', count: 0, subNames: ['Vue Composition API'] },
    { mainName: 'Vuetify', count: 0, subNames: ['Vuetify'] },
    { mainName: 'Signals', count: 0, subNames: ['Signals'] },
    { mainName: 'Reactive programming', count: 0, subNames: ['Reactive programming'] },
    { mainName: 'Java', count: 0, subNames: ['Java'] },
    { mainName: 'Cententful', count: 0, subNames: ['Cententful'] },
    { mainName: 'Contentstack', count: 0, subNames: ['Contentstack'] },
    { mainName: 'Kentico', count: 0, subNames: ['Kentico'] },
    { mainName: 'SCSS', count: 0, subNames: ['SCSS'] },
    { mainName: 'Sitecore JSS', count: 0, subNames: ['Sitecore JSS'] },
    { mainName: 'ISR', count: 0, subNames: ['ISR'] },
    { mainName: 'Django', count: 0, subNames: ['Django'] },
    { mainName: 'Microfrontends', count: 0, subNames: ['Microfrontends'] },
    { mainName: 'Serverless architectures', count: 0, subNames: ['Serverless architectures'] },
    { mainName: 'Developer automation', count: 0, subNames: ['Developer automation'] },
    { mainName: 'D3.js', count: 0, subNames: ['D3.js'] },
{ mainName: 'visx', count: 0, subNames: ['visx'] },


    //
    //
];
