import { JobEntry } from '../../../types';

export default <JobEntry[]>[
    {
        dateCreated: 1763830348,
        companyName: 'Deel',
        jobTitle: 'Senior Frontend Engineer, React.js',
        workMode: 'Remote',
        yearsOfExperience: 8,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'TypeScript',
            'React.js',
            'React Class Components',
            'React Functional Components',
            'React Hooks',
            'State management tools',
            'HTML',
            'CSS',
            'Node.js',
            'SaaS experience',
            'Cloud platforms',
            'Pixel-perfect UI implementation',
            'Subscription management',
            'Access auditing',
            'FinTech knowledge'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Ownership',
            'Teamwork',
            'Problem-solving',
            'Optimism',
            'Business-focused thinking',
            'Genuine care for users',
            'Working in distributed teams',
            'Independence'
        ]
    },
    {
        dateCreated: 1763830363,
        companyName: 'Distilled (DoneDeal / Adverts)',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'HTML',
            'CSS',
            'JavaScript',
            'TypeScript',
            'React',
            'Next.js',
            'REST APIs',
            'Responsive design',
            'Mobile-first development',
            'Jest',
            'Cypress',
            'Playwright',
            'GitHub Copilot',
            'Claude Code',
            'Cursor',
            'Node.js',
            'Web performance',
            'Webpack',
            'Styled Components',
            'Storybook',
            'Monorepos',
            'Design systems'
        ],
        softSkills: [
            'Communication',
            'Collaboration',
            'Mentoring',
            'Independent work',
            'Problem-solving',
            'Initiative',
            'Usability focus',
            'Code quality advocacy',
            'Keeping up with new technologies'
        ]
    },
    {
        dateCreated: 1763830348,
        companyName: 'Zinkworks',
        jobTitle: 'Senior React UI Developer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'React Class Components',
            'React Functional Components',
            'React Hooks',
            'HTML',
            'CSS',
            'Frontend architecture',
            'Performance optimization',
            'Accessibility',
            'Git',
            'Agile development',
            'Jira',
            'Confluence',
            'UI/UX design without UX support',
            'Data-heavy interfaces',
            'Docker',
            'CI/CD pipelines',
            'FlutterFlow',
            'Streamlit'
        ],
        softSkills: [
            'Ownership',
            'Autonomy',
            'Collaboration',
            'Communication',
            'Problem-solving',
            'Teamwork',
            'Adaptability',
            'High performance mindset',
            'Decision-making',
            'Working in distributed teams'
        ]
    },
    {
        dateCreated: 1763830348,
        companyName: 'Monad Foundation',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'Next.js',
            'TypeScript',
            'Svelte',
            'SvelteKit',
            'Design systems',
            'Component libraries',
            'Tokens and theming',
            'Figma to production UI',
            'Animations',
            'Micro-interactions',
            'Framer Motion',
            'GSAP',
            'Accessibility',
            'ARIA',
            'Keyboard support',
            'Color contrast standards',
            'Responsive design',
            'Container queries',
            'CSS Grid',
            'Flexbox',
            'CSS custom properties',
            'Tailwind CSS',
            'shadcn/ui',
            'Performance optimization',
            'Bundle size optimization',
            'Code splitting',
            'Hydration strategies',
            'Caching strategies',
            'Virtualization',
            'React Query',
            'SWR',
            'Wallet integrations',
            'WalletConnect',
            'Injected providers',
            'On-chain data rendering',
            'RPC/indexer integration',
            'State management for loading/skeleton/error',
            'Testing best practices',
            'CI checks',
            'Documentation',
            'Git',
            'UI refactoring',
            'Playwright',
            'Testing Library',
            'Storybook',
            'Chromatic',
            'Visual regression testing',
            'Style Dictionary',
            'Performance tooling',
            'Lighthouse',
            'WebPageTest',
            'Perfetto',
            'Monitoring tools',
            'Sentry',
            'Datadog',
            'New Relic',
            'i18n',
            'RTL support',
            'WebGL',
            'Canvas',
            'SVG'
        ],
        softSkills: [
            'Ownership',
            'Autonomy',
            'Attention to detail',
            'Collaboration',
            'Communication',
            'Systems thinking',
            'Pragmatism',
            'Consistency',
            'Clear documentation',
            'Self-direction',
            'Feedback culture',
            'Quality mindset'
        ]
    }
];
