import { JobEntry } from '../types';

export default <JobEntry[]>[
    {
        dateCreated: 1763830348000,
        companyName: 'Deel',
        jobTitle: 'Senior Frontend Engineer, React.js',
        workMode: 'Remote',
        yearsOfExperience: 8,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'TypeScript',
            'React.js',
            'React Class Components',
            'React Functional Components',
            'React Hooks',
            'State management tools',
            'HTML',
            'CSS',
            'Node.js',
            'SaaS experience',
            'Cloud platforms',
            'Pixel-perfect UI implementation',
            'Subscription management',
            'Access auditing',
            'FinTech knowledge'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Ownership',
            'Teamwork',
            'Problem-solving',
            'Optimism',
            'Business-focused thinking',
            'Genuine care for users',
            'Working in distributed teams',
            'Independence'
        ]
    },
    {
        dateCreated: 1763830363000,
        companyName: 'Distilled (DoneDeal / Adverts)',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'HTML',
            'CSS',
            'JavaScript',
            'TypeScript',
            'React',
            'Next.js',
            'REST APIs',
            'Responsive design',
            'Mobile-first development',
            'Jest',
            'Cypress',
            'Playwright',
            'GitHub Copilot',
            'Claude Code',
            'Cursor',
            'Node.js',
            'Web performance',
            'Webpack',
            'Styled Components',
            'Storybook',
            'Monorepos',
            'Design systems'
        ],
        softSkills: [
            'Communication',
            'Collaboration',
            'Mentoring',
            'Independent work',
            'Problem-solving',
            'Initiative',
            'Usability focus',
            'Code quality advocacy',
            'Keeping up with new technologies'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Zinkworks',
        jobTitle: 'Senior React UI Developer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'React Class Components',
            'React Functional Components',
            'React Hooks',
            'HTML',
            'CSS',
            'Frontend architecture',
            'Performance optimization',
            'Accessibility',
            'Git',
            'Agile development',
            'Jira',
            'Confluence',
            'UI/UX design without UX support',
            'Data-heavy interfaces',
            'Docker',
            'CI/CD pipelines',
            'FlutterFlow',
            'Streamlit'
        ],
        softSkills: [
            'Ownership',
            'Autonomy',
            'Collaboration',
            'Communication',
            'Problem-solving',
            'Teamwork',
            'Adaptability',
            'High performance mindset',
            'Decision-making',
            'Working in distributed teams'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Monad Foundation',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'Next.js',
            'TypeScript',
            'Svelte',
            'SvelteKit',
            'Design systems',
            'Component libraries',
            'Tokens and theming',
            'Figma to production UI',
            'Animations',
            'Micro-interactions',
            'Framer Motion',
            'GSAP',
            'Accessibility',
            'ARIA',
            'Keyboard support',
            'Color contrast standards',
            'Responsive design',
            'Container queries',
            'CSS Grid',
            'Flexbox',
            'CSS custom properties',
            'Tailwind CSS',
            'shadcn/ui',
            'Performance optimization',
            'Bundle size optimization',
            'Code splitting',
            'Hydration strategies',
            'Caching strategies',
            'Virtualization',
            'React Query',
            'SWR',
            'Wallet integrations',
            'WalletConnect',
            'Injected providers',
            'On-chain data rendering',
            'RPC/indexer integration',
            'State management for loading/skeleton/error',
            'Testing best practices',
            'CI checks',
            'Documentation',
            'Git',
            'UI refactoring',
            'Playwright',
            'Testing Library',
            'Storybook',
            'Chromatic',
            'Visual regression testing',
            'Style Dictionary',
            'Performance tooling',
            'Lighthouse',
            'WebPageTest',
            'Perfetto',
            'Monitoring tools',
            'Sentry',
            'Datadog',
            'New Relic',
            'i18n',
            'RTL support',
            'WebGL',
            'Canvas',
            'SVG'
        ],
        softSkills: [
            'Ownership',
            'Autonomy',
            'Attention to detail',
            'Collaboration',
            'Communication',
            'Systems thinking',
            'Pragmatism',
            'Consistency',
            'Clear documentation',
            'Self-direction',
            'Feedback culture',
            'Quality mindset'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Restream',
        jobTitle: 'Senior Software Engineer - Frontend',
        workMode: 'Remote',
        yearsOfExperience: 0,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'React.js',
            'State management systems',
            'MobX',
            'CSS',
            'LESS',
            'SASS',
            'Node.js',
            'REST APIs',
            'Relational databases',
            'NoSQL databases',
            'AWS',
            'Linux',
            'Docker',
            'Kubernetes',
            'Continuous deployment'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Entrepreneurial attitude',
            'Attention to detail',
            'Design sensibility',
            'Analytical thinking',
            'Self-directed',
            'Teamwork',
            'User-focused mindset'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Confidential Global Software Company',
        jobTitle: 'Senior Frontend Developer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'HTML5',
            'CSS3',
            'React.js',
            'Angular',
            'Vue.js',
            'State management libraries',
            'RESTful APIs',
            'Webpack',
            'Vite',
            'Responsive design',
            'Web performance optimization',
            'UX best practices',
            'Git',
            'Agile development'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Leadership',
            'Mentorship',
            'Problem-solving',
            'Attention to detail',
            'Creativity',
            'Innovation',
            'Autonomy',
            'Teamwork'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Confidential Blockchain Startup',
        jobTitle: 'Senior Software Engineer - Web3 & Cross-Chain DApps',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'TypeScript',
            'React.js',
            'Next.js',
            'XState',
            'Wagmi',
            'React Native',
            'UI/UX design',
            'Frontend optimization',
            'SDK development',
            'Cross-chain DApps',
            'Blockchain technology',
            'DeFi platforms',
            'Observability and tracing',
            'State machines',
            'Mobile, tablet, and desktop frontend development',
            'Code quality',
            'Code maintainability'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Problem-solving',
            'Attention to detail',
            'UI/UX sensibility',
            'Autonomy',
            'Teamwork',
            'Cross-timezone collaboration',
            'Startup mindset'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Proxify',
        jobTitle: 'Senior Software Developer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'Next.js',
            'Node.js',
            'JavaScript (ES6+)',
            'TypeScript',
            'HTML5',
            'CSS3',
            'CSS-in-JS',
            'State management libraries',
            'Redux',
            'Zustand',
            'Recoil',
            'RESTful APIs',
            'Asynchronous operations',
            'Frontend-backend integration',
            'Unit testing',
            'Integration testing',
            'Jest',
            'React Testing Library',
            'Webpack',
            'Vite',
            'Performance optimization',
            'Accessibility',
            'CI/CD pipelines',
            'GraphQL',
            'gRPC',
            'Backend technologies',
            'Backend databases',
            'Cloud services',
            'Modular component design',
            'Design systems',
            'Component libraries'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Problem-solving',
            'Attention to detail',
            'Autonomy',
            'Teamwork',
            'Agile mindset',
            'Creativity',
            'User-focused mindset',
            'Fast-paced environment adaptability'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Intercom',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'JavaScript',
            'HTML',
            'CSS',
            'Node.js',
            'SaaS product development',
            'Frontend architecture',
            'Design systems',
            'Localization',
            'Build tooling',
            'Observability',
            'Unit testing',
            'Code reviews',
            'Design documentation',
            'Technical mentoring',
            'Performance optimization',
            'Reliability best practices'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Leadership',
            'Mentorship',
            'Problem-solving',
            'Autonomy',
            'Teamwork',
            'Attention to detail',
            'Technical articulation',
            'Persistence',
            'Learning agility'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Bentley Systems',
        jobTitle: 'Senior Software Engineer (TypeScript / JavaScript / React)',
        workMode: 'Hybrid',
        yearsOfExperience: 6,
        bachelorDegree: true,
        mastersDegree: true,
        hardSkills: [
            'TypeScript',
            'JavaScript',
            'React.js',
            'Node.js',
            'Unit testing',
            'Test-driven development',
            'Object-Oriented Programming (OOP)',
            'SOLID principles',
            'DRY principles',
            'Software design principles',
            'Software Development Life Cycle (SDLC)',
            'Agile / Scrum',
            'Git',
            'C++',
            'C#',
            '.NET',
            'Azure DevOps',
            'Backlog management',
            'Jira',
            'TFS',
            'ADO',
            'Software design diagrams',
            'Mathematical foundations (Geometry, Trigonometry)',
            'Infrastructure software knowledge'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Problem-solving',
            'Analytical thinking',
            'Attention to detail',
            'Ownership',
            'Mentorship',
            'Teamwork',
            'Continuous learning',
            'Adaptability'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Dataminr',
        jobTitle: 'Frontend Software Engineer III',
        workMode: 'Remote',
        yearsOfExperience: 4,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'JavaScript',
            'TypeScript',
            'React Hooks',
            'React Context',
            'React Suspense',
            'Concurrent React features',
            'State management',
            'TanStack Query',
            'Zustand',
            'Component libraries',
            'Design systems',
            'REST APIs',
            'GraphQL (queries, mutations, caching, fragments)',
            'Unit testing',
            'Jest',
            'Vitest',
            'Component testing',
            'Integration testing',
            'React Testing Library',
            'E2E testing',
            'Cypress',
            'Playwright',
            'Frontend architecture',
            'Performance optimization',
            'Modern frontend patterns'
        ],
        softSkills: [
            'Problem-solving',
            'Collaboration',
            'Communication',
            'Attention to detail',
            'Autonomy',
            'Teamwork',
            'Fast-paced environment adaptability',
            'Technical reasoning',
            'Feature delivery focus',
            'Learning agility'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Squarespace',
        jobTitle: 'Senior Frontend Engineer - International Team',
        workMode: 'Hybrid',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'TypeScript',
            'Frontend architecture',
            'Testing best practices',
            'Performance optimization',
            'Maintainable code',
            'Maintainable architecture',
            'Internationalization',
            'i18n',
            'Localization',
            'Translation workflows',
            'Component libraries',
            'Design systems',
            'Collaboration with designers',
            'Collaboration with product managers'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Mentorship',
            'Problem-solving',
            'Attention to detail',
            'Autonomy',
            'Teamwork',
            'Technical articulation',
            'Cross-disciplinary communication',
            'Inclusive mindset'
        ]
    },
    {
        dateCreated: 1763919427667,
        companyName: 'Canto',
        jobTitle: 'Senior Frontend Software Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'React Hooks',
            'React Context',
            'React Routing',
            'Component composition',
            'TypeScript',
            'JavaScript (ES6+)',
            'HTML',
            'CSS',
            'Tailwind CSS',
            'Material UI (MUI)',
            'TanStack Query',
            'Figma',
            'WCAG accessibility',
            'Frontend performance optimization',
            'Unit testing',
            'Jest',
            'React Testing Library',
            'Integration testing',
            'Component testing',
            'Playwright',
            'CI/CD practices',
            'Agile workflow'
        ],
        softSkills: [
            'Problem-solving',
            'Collaboration',
            'Communication',
            'Mentorship',
            'Teamwork',
            'Attention to detail',
            'Autonomy',
            'Creativity',
            'Adaptability',
            'Proactive learning'
        ]
    },
    {
        dateCreated: 1763919427667,
        companyName: 'Pragmatike',
        jobTitle: 'Senior/Lead Frontend Developer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: true,
        hardSkills: [
            'React.js',
            'Redux.js',
            'JavaScript (ES6+)',
            'TypeScript',
            'Node.js',
            'HTML5',
            'CSS3',
            'SPA development',
            'Reusable UI components',
            'Object-Oriented JavaScript',
            'Object-Oriented Programming',
            'Unit testing',
            'Performance optimization',
            'UI testing',
            'Selenium',
            'Front-end tooling',
            'ESLint',
            'Prettier',
            'Responsive design',
            'Micro Frontend Applications'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Problem-solving',
            'Mentorship',
            'Attention to detail',
            'Creativity',
            'Proactive learning',
            'Autonomy',
            'Teamwork',
            'Adaptability'
        ]
    },
    {
        dateCreated: 1763919427667,
        companyName: 'BrainRocket',
        jobTitle: 'Senior Angular Developer',
        workMode: 'On-site',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Angular 2+',
            'Angular 15',
            'TypeScript',
            'Web development',
            'REST APIs',
            'Jest',
            'Testing frameworks',
            'Test runner frameworks',
            'SOLID principles',
            'GRASP principles',
            'Client-side architecture',
            'Design patterns',
            'Cross-browser compatibility',
            'Performance optimization',
            'Git',
            'npm',
            'Webpack',
            'Babel',
            'Linters',
            'Nx framework',
            'TypeScript AST',
            'Code modifiers',
            'GitLab',
            'CI/CD',
            'Docker',
            'NGINX',
            'Node.js',
            'UX understanding'
        ],
        softSkills: [
            'Problem-solving',
            'Learning skills',
            'Ability to work independently',
            'Technical advice and mentorship',
            'Task coordination',
            'Communication',
            'Attention to detail',
            'Team collaboration',
            'Strong product mindset'
        ]
    },
    {
        dateCreated: 1764096000000,
        companyName: 'Tiger Data',
        jobTitle: 'Senior Front-End Engineer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'TypeScript',
            'React',
            'JavaScript',
            'UI/UX implementation',
            'Pixel-perfect UI',
            'Cypress',
            'testing',
            'End-to-end testing',
            'API development',
            'Backend API layer experience',
            'SQL',
            'Data-driven query languages',
            'SaaS product development',
            'Cloud services UI development',
            'Golang',
            'PostgreSQL',
            'Docker',
            'Kubernetes',
            'AWS',
            'Data visualization',
            'modern frameworks'
        ],
        softSkills: [
            'Ownership',
            'Self-driven execution',
            'Strong communication',
            'Attention to detail',
            'Collaboration',
            'Working with product and design',
            'Customer-centric thinking',
            'Ability to thrive in fast-paced environments',
            'Remote teamwork'
        ]
    },
    {
        dateCreated: 1764096000000,
        companyName: 'Primus Global Solutions',
        jobTitle: 'Senior Frontend Developer',
        workMode: 'Hybrid',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React',
            'Next.js',
            'TypeScript',
            'Vue',
            'AI-powered solutions',
            'Chatbots',
            'LLM workflows',
            'OpenAI GPT',
            'SSR',
            'SSG',
            'Component libraries',
            'Dashboards',
            'Accessibility',
            'ally',
            'Performance optimisation',
            'HTML5',
            'CSS3',
            'JavaScript/ES6+',
            'AngularJS',
            'Node.js',
            'MobX',
            'Redux',
            'Tailwind CSS',
            'MUI',
            'Styled Components',
            'WordPress',
            'Joomla',
            'Drupal',
            'Cockpit CMS',
            'Agile teamwork'
        ],
        softSkills: ['Agile teamwork']
    },
    {
        dateCreated: 1764096000000,
        companyName: 'Refurbed',
        jobTitle: 'Senior Frontend Engineer - Delivery & Returns',
        workMode: 'Remote',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Vue',
            'TypeScript',
            'modern JavaScript',
            'semantic HTML',
            'CSS',
            'responsive layout',
            'Core Web Vitals',
            'runtime performance',
            'accessibility',
            'state management',
            'routing',
            'modularization',
            'component library',
            'design system',
            'legacy code refactoring',
            'architectural improvements',
            'API collaboration'
        ],
        softSkills: ['communication', 'mentorship', 'collaboration']
    },
    {
        dateCreated: 1764096000000,
        companyName: 'Confidential UAE Startup',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'On-site',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: ['React.js', 'TypeScript', 'testing', 'large-scale applications'],
        softSkills: ['communication', 'confidence', 'collaboration']
    },
    {
        dateCreated: 1764096000000,
        companyName: 'Flywheel',
        jobTitle: 'Senior Frontend Engineer - Delivery & Returns',
        workMode: 'Hybrid',
        yearsOfExperience: 8,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'Angular (13+)',
            'TypeScript',
            'JavaScript (ES6+)',
            'State management libraries',
            'HTML5',
            'CSS3',
            'SASS',
            'RESTful APIs',
            'Responsive design',
            'UI/UX best practices',
            'Accessibility (WCAG)',
            'Front-end build tools',
            'Testing frameworks',
            'Jasmine',
            'Karma',
            'Cypress',
            'CI/CD pipelines',
            'Agile Project Management tools',
            'Jira',
            'Git',
            'Version control',
            'Design systems',
            'Refactoring',
            'Performance optimization'
        ],
        softSkills: [
            'Communication',
            'Collaboration',
            'Analytical thinking',
            'Problem-solving',
            'Mentorship',
            'Teamwork',
            'Autonomy'
        ]
    },
    {
        dateCreated: 1764091820000,
        companyName: 'Sitecore',
        jobTitle: 'Senior Frontend Developer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'React',
            'TypeScript',
            'Shadcn UI components',
            'Tailwind CSS',
            'Tanstack Router',
            'Tanstack libraries',
            'Vite',
            'Github',
            'Frontend build tools',
            'Code reviews',
            'Containerized application development',
            'AWS cloud services',
            'Automation testing',
            'Version control'
        ],
        softSkills: ['Problem-solving', 'Architectural decision-making', 'Collaboration', 'Leadership', 'Innovation']
    },
    {
        dateCreated: 1764091931000,
        companyName: 'ClickUp',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Angular 2+',
            'JavaScript',
            'TypeScript',
            'NgRx',
            'RxJS',
            'HTML',
            'CSS',
            'Reusable UI components',
            'State management',
            'Unit testing',
            'Integration testing',
            'Performance optimization',
            'Cross-browser compatibility',
            'Accessibility'
        ],
        softSkills: [
            'Problem-solving',
            'Self-starter',
            'Operational focus',
            'Collaboration',
            'Communication',
            'Mentorship'
        ]
    },
    {
        dateCreated: 1764092004000,
        companyName: 'Amazon Web Services (AWS)',
        jobTitle: 'Senior Frontend Development Engineer',
        workMode: 'On-site',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'HTML',
            'CSS',
            'JavaScript',
            'TypeScript',
            'Node.js',
            'React',
            'State management patterns',
            'RESTful APIs',
            'Modern build tools',
            'Webpack',
            'Vite',
            'AWS/cloud technologies',
            'Relational databases',
            'MySQL',
            'SQL querying tools'
        ],
        softSkills: [
            'Mentorship',
            'Technical leadership',
            'Problem-solving',
            'Collaboration',
            'Communication',
            'Curiosity',
            'Explorative mindset',
            'Attention to detail'
        ]
    },
    {
        dateCreated: 1764150193000,
        companyName: 'Remote',
        jobTitle: 'Senior Frontend Engineer (Website Team)',
        workMode: 'Remote',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Node.js',
            'React',
            'Next.js',
            'TypeScript',
            'JavaScript',
            'Semantic HTML',
            'CSS',
            'SEO best practices',
            'Web performance optimization',
            'Performance audits',
            'Third-party APIs',
            'Analytics integrations',
            'Headless CMS integrations',
            'Postgres (context)',
            'Elixir/Phoenix (context)',
            'CI/CD',
            'Gitlab',
            'AWS hosting'
        ],
        softSkills: [
            'Independent work',
            'Self-guidance',
            'Curiosity',
            'Willingness to learn',
            'Collaboration with Marketing and Sales',
            'Handling ambiguity',
            'Transforming abstract concepts into working software'
        ]
    },
    {
        dateCreated: 1764150336000,
        companyName: 'Sonatus',
        jobTitle: 'Senior Fullstack Software Engineer',
        workMode: 'On-site',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'TypeScript',
            'JavaScript',
            'React.js',
            'Node.js',
            'GraphQL',
            'REST APIs',
            'Express.js',
            'Ant Design',
            'Frontend component-based architecture',
            'State management',
            'PostgreSQL',
            'MySQL',
            'Relational databases',
            'MongoDb',
            'DynamoDb',
            'NoSQL databases',
            'Database schema design',
            'Database performance optimization',
            'Unit testing',
            'Integration testing',
            'End-to-end testing',
            'AWS',
            'GCP',
            'Azure',
            'Cloud platforms',
            'Docker',
            'Kubernetes',
            'Containerization',
            'Scalable backend systems',
            'Fullstack web application development'
        ],
        softSkills: [
            'Proactive problem-solving',
            'Collaboration with Product, UX, QA teams',
            'Leadership in technical discussions',
            'Knowledge sharing',
            'Engineering excellence',
            'Developer tooling improvements',
            'Continuous learning'
        ]
    },
    {
        dateCreated: 1764165165000,
        companyName: 'Kraken',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Software development',
            'Web applications',
            'JavaScript',
            'TypeScript',
            'React',
            'API design',
            'Security',
            'Performance optimization',
            'Next.js',
            'WebSockets',
            'Frontend testing frameworks',
            'Modern front-end build pipelines',
            'Modern front-end tooling',
            'UI/UX best practices',
            'Experience in large technology organizations',
            'Experience in fast growing startups',
            'Consumer payments experience',
            'Crypto applications experience',
            'Fintech mobile applications experience',
            'Scalable system design',
            'Maintainable system design',
            'Fault-tolerant system design',
            'Software architecture',
            'Design patterns'
        ],
        softSkills: [
            'Strong written communication',
            'Strong verbal communication',
            'Mentoring junior and senior engineers',
            'Providing constructive feedback',
            'Influencing technical decisions',
            'Contributing to technical strategy',
            'Leading complex initiatives',
            'Driving process improvements',
            'Collaboration across teams'
        ]
    },
    {
        dateCreated: 1764165254000,
        companyName: 'Lumenalta',
        jobTitle: 'Senior React Developer',
        workMode: 'Remote',
        yearsOfExperience: 7,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'JavaScript',
            'React',
            'Redux',
            'WebSockets',
            'Async/Await',
            'Clean code',
            'Testable code',
            'Well-documented code'
        ],
        softSkills: [
            'Problem solving',
            'Proactive',
            'Go-getter',
            'Team player',
            'Professional',
            'Empathic',
            'Advanced English fluency'
        ]
    },
    {
        dateCreated: 1764165459000,
        companyName: 'Yahoo',
        jobTitle: 'Principal Software Engineer',
        workMode: 'Remote',
        yearsOfExperience: 8,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'React',
            'Next.js',
            'Angular',
            'Ember',
            'Node.js',
            'HTML5',
            'CSS3',
            'AJAX',
            'Responsive web design',
            'Redux Toolkit',
            'Storybook',
            'Atomic CSS',
            'Superagent',
            'Web Vitals',
            'JSON',
            'REST APIs',
            'Test-driven development',
            'Jest',
            'Selenium',
            'WebdriverIO',
            'React Testing Library',
            'Mock Service Worker',
            'Playwright',
            'Web performance optimization',
            'Application stability',
            'Debugging large-scale web applications'
        ],
        softSkills: [
            'Collaboration with global teams',
            'Communication',
            'Professionalism',
            'Empathy',
            'Problem-solving',
            'Attention to detail',
            'Mentorship',
            'Continuous learning'
        ]
    },
    {
        dateCreated: 1764165542000,
        companyName: 'Solance',
        jobTitle: 'Senior UI Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React Native',
            'React',
            'UI & UX design',
            'Figma',
            'Figma to pixel-perfect implementation',
            'iOS development',
            'Android development',
            'Web development',
            'Multi-channel deployment',
            'MFA implementation',
            'SSO',
            'Offline-first applications',
            'Local storage',
            'Deep linking',
            'Notifications',
            'Accessibility',
            'Internationalization',
            'Atomic design',
            'UI testing',
            'UI code deployment',
            'Release management',
            'Observability',
            'User behavior tracking',
            'Alerting principles',
            'DevOps/SRE automation for UI deployments',
            'AI tooling',
            'Visual design',
            'Cross-channel UI frameworks'
        ],
        softSkills: [
            'Mentorship',
            'Collaboration with business and product teams',
            'Agile software development',
            'Business analysis',
            'Scrum Master skills',
            'Problem-solving',
            'Proactive automation mindset',
            'Team leadership',
            'Attention to detail',
            'Customer-centric thinking'
        ]
    },
    {
        dateCreated: 1764165643000,
        companyName: 'TryHackMe',
        jobTitle: 'Senior Software Engineer (Full-Stack)',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'NodeJS',
            'React',
            'Redux',
            'MongoDB',
            'AWS',
            'CSS',
            'HTML',
            'jQuery',
            'MERN stack',
            'Software architecture',
            'Design principles',
            'CI/CD pipelines',
            'Cloud platforms',
            'Agile',
            'Scrum',
            'Fullstack development',
            'Database design',
            'Query optimization',
            'System performance monitoring',
            'Software development processes'
        ],
        softSkills: [
            'Mentorship',
            'Leadership',
            'Problem-solving',
            'Collaboration with product, design, and engineering teams',
            'Communication',
            'Proactive learning',
            'Team coaching',
            'Technical guidance',
            'Adaptability',
            'Start-up / scale-up experience'
        ]
    },
    {
        dateCreated: 1764165762000,
        companyName: 'BeyondBMI',
        jobTitle: 'Senior Frontend Software Engineer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React Native',
            'Next.js',
            'Storybook',
            'React Router',
            'JavaScript',
            'RESTful APIs',
            'State management',
            'Zustand',
            'Jest',
            'Unit testing',
            'Automated testing',
            'Version control',
            'Frontend architecture',
            'Clean code',
            'Maintainable code',
            'Reusable code'
        ],
        softSkills: [
            'Collaboration',
            'Autonomy',
            'Attention to detail',
            'Methodical work process',
            'Coaching and mentoring',
            'Code reviews',
            'Problem-solving',
            'Continuous learning',
            'Technical innovation',
            'Creativity in solutions',
            'Proactivity',
            'Challenging the norm'
        ]
    },
    {
        dateCreated: 1764165848000,
        companyName: 'Datavant',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'TypeScript',
            'JavaScript',
            'React',
            'Vue',
            'Angular',
            'HTML',
            'CSS',
            'Responsive design',
            'Accessibility (WCAG)',
            'Design systems',
            'Component libraries',
            'Unit testing',
            'End-to-end testing',
            'Jest',
            'Testing Library',
            'Cypress',
            'Frontend migrations',
            'Greenfield development',
            'modular code',
            'maintainable code',
            'Python',
            'Spark',
            'Snowflake',
            'AWS',
            'Azure'
        ],
        softSkills: [
            'Collaboration with product designers and backend engineers',
            'Cross-functional teamwork',
            'Mentoring and coaching',
            'Ownership of projects',
            'Self-motivation',
            'Adaptability',
            'Problem-solving',
            'Attention to detail',
            'Technical excellence',
            'Communication skills',
            'Passion for healthcare and impact-driven work'
        ]
    },
    {
        dateCreated: 1764165955000,
        companyName: 'Centripetal Networks',
        jobTitle: 'Software UI Engineer, CIS Cloud Services',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: true,
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'React',
            'Material UI',
            'Storybook',
            'SPA development',
            'PWA',
            'Web Workers',
            'Web Sockets',
            'RESTful Services',
            'GraphQL',
            'CQRS',
            'CI/CD',
            'DevOps',
            'SecDevOps',
            'UX process',
            'Frontend development',
            'Backend integration',
            'Efficient data handling'
        ],
        softSkills: [
            'Collaborative problem-solving',
            'Ownership and impact',
            'Continuous self-improvement',
            'Innovation mindset',
            'Customer-focused development',
            'Communication skills',
            'Adaptability',
            'Team collaboration'
        ]
    },
    {
        dateCreated: 1764166076000,
        companyName: 'Jibble Group',
        jobTitle: 'Senior Frontend Developer (Vue.js)',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Vue.js',
            'Vue 3',
            'Vue Composition API',
            'JavaScript',
            'TypeScript',
            'Material Design',
            'Vuetify',
            'Frontend web development',
            'Pixel-perfect UI implementation',
            'Unit testing',
            'Web client development',
            'Refactoring',
            'Agile',
            'Scrum'
        ],
        softSkills: [
            'Collaboration with product managers and designers',
            'Code review and mentoring',
            'Continuous learning',
            'Attention to detail',
            'Remote teamwork',
            'Communication skills',
            'Adaptability',
            'Problem-solving'
        ]
    },
    {
        dateCreated: 1764166161000,
        companyName: 'LimeFlight',
        jobTitle: 'Senior Frontend Engineer (Angular)',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'Angular 20',
            'RxJS',
            'Signals',
            'NgRx',
            'JavaScript',
            'TypeScript',
            'Unit testing',
            'Karma',
            'Jasmine',
            'Integration testing',
            'Cypress',
            'Playwright',
            'GitHub Actions',
            'Frontend architecture',
            'Component library management',
            'Figma',
            'Storybook',
            'Design Systems',
            'Reactive programming',
            'UI/UX development',
            'Reusable code design'
        ],
        softSkills: [
            'Collaboration with designers, product managers, and backend engineers',
            'Problem-solving',
            'Continuous learning',
            'Ability to explain trade-offs to non-technical stakeholders',
            'Attention to maintainability and quality',
            'Communication skills',
            'Adaptability',
            'Team-oriented mindset'
        ]
    },
    {
        dateCreated: 1764166253000,
        companyName: 'Apata',
        jobTitle: 'Senior Frontend Developer',
        workMode: 'On-site',
        yearsOfExperience: 4,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'JavaScript (ES6+)',
            'TypeScript',
            'HTML',
            'CSS',
            'UI/UX implementation',
            'Frontend optimization',
            'Responsive design',
            'Browser testing',
            'Debugging',
            'Performance optimization',
            'Build tools',
            'Web development lifecycle',
            'Component-based architecture',
            'Technical documentation'
        ],
        softSkills: [
            'Collaboration with backend engineers and designers',
            'Detail-oriented',
            'Self-motivated',
            'Positive mindset',
            'Problem-solving',
            'Adaptability',
            'User-focused development',
            'Team player'
        ]
    },
    {
        dateCreated: 1764166376000,
        companyName: 'NETGEAR',
        jobTitle: 'Senior Software Engineer (Web)',
        workMode: 'Hybrid',
        yearsOfExperience: 8,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'Vue.js',
            'JavaScript',
            'Node.js',
            'Java',
            'Python',
            'TypeScript',
            'SPA development',
            'PWA development',
            'Frontend architecture',
            'Cententful',
            'Contentstack',
            'Kentico',
            'CMS',
            'Agile development',
            'Web performance optimization',
            'SEO compliance',
            'Integration of third-party services',
            'Technical leadership',
            'Code review',
            'Code mentorship'
        ],
        softSkills: [
            'Collaboration with cross-functional teams',
            'Communication',
            'Proactive problem-solving',
            'Resourcefulness',
            'Mentorship',
            'Teamwork',
            'Strategic thinking',
            'Adaptability in fast-paced environments'
        ]
    },
    {
        dateCreated: 1764166464000,
        companyName: 'Henry Schein, Inc.',
        jobTitle: 'Sr Front-End Developer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'Angular (v8+)',
            'TypeScript',
            'HTML5',
            'CSS3',
            'SCSS',
            'Responsive web design',
            'Next.js',
            'Sitecore JSS',
            'RESTful APIs',
            'GraphQL',
            'Web Sockets',
            'Git',
            'CI/CD pipelines',
            'Webpack',
            'Nx',
            'SSR',
            'SSG',
            'ISR',
            'Performance profiling',
            'Lazy loading',
            'Code splitting',
            'Accessibility (WCAG)',
            'SEO optimization',
            'Cypress',
            'Jest',
            'Playwright',
            'Testing frameworks'
        ],
        softSkills: [
            'Collaboration with cross-functional teams',
            'Problem-solving',
            'Attention to detail',
            'Professional behavior',
            'Mentorship',
            'Adaptability',
            'Strong communication'
        ]
    },
    {
        dateCreated: 1764166597000,
        companyName: 'ReversingLabs',
        jobTitle: 'Senior Software Engineer',
        workMode: 'Remote',
        yearsOfExperience: 7,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'TypeScript',
            'React',
            'HTML5',
            'CSS3',
            'Python',
            'OO languages',
            'Frontend and backend tooling setup',
            'Docker',
            'Redux Toolkit',
            'Material-UI',
            'Webpack',
            'Storybook',
            'Django',
            'PostgreSQL',
            'Secure coding practices',
            'UX design translation to UI'
        ],
        softSkills: [
            'Independent problem-solving',
            'Team collaboration',
            'Technical ownership',
            'Architectural decision-making',
            'Continuous learning',
            'Strong communication skills'
        ]
    },
    {
        dateCreated: 1764166693000,
        companyName: 'epilot',
        jobTitle: 'Senior Product Engineer (Frontend)',
        workMode: 'Remote',
        yearsOfExperience: 4,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'JavaScript (ES6+)',
            'Hooks',
            'state management',
            'routing',
            'React',
            'TypeScript',
            'Webpack',
            'ESLint',
            'Unit testing',
            'end-to-end testing',
            'HTML',
            'CSS',
            'GraphQL',
            'Node.js',
            'AWS',
            'Microfrontends',
            'Serverless architectures',
            'Developer tooling',
            'Developer automation'
        ],
        softSkills: [
            'Collaboration in cross-functional teams',
            'Product mindset',
            'Problem-solving',
            'Agile methodology',
            'User-focused development',
            'Ownership & accountability',
            'Continuous learning'
        ]
    }
];
