import { JobEntry } from '../types';

export default [
    {
        dateCreated: 1763830348000,
        companyName: 'Deel',
        jobTitle: 'Senior Frontend Engineer, React.js',
        workMode: 'Remote',
        yearsOfExperience: 8,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'TypeScript',
            'React.js',
            'React Class Components',
            'React Functional Components',
            'React Hooks',
            'State management tools',
            'HTML',
            'CSS',
            'Node.js',
            'SaaS experience',
            'Cloud platforms',
            'Pixel-perfect UI implementation',
            'Subscription management',
            'Access auditing',
            'FinTech knowledge'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Ownership',
            'Teamwork',
            'Problem-solving',
            'Optimism',
            'Business-focused thinking',
            'Genuine care for users',
            'Working in distributed teams',
            'Independence'
        ]
    },
    {
        dateCreated: 1763830363000,
        companyName: 'Distilled (DoneDeal / Adverts)',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'HTML',
            'CSS',
            'JavaScript',
            'TypeScript',
            'React',
            'Next.js',
            'REST APIs',
            'Responsive design',
            'Mobile-first development',
            'Jest',
            'Cypress',
            'Playwright',
            'GitHub Copilot',
            'Claude Code',
            'Cursor',
            'Node.js',
            'Web performance',
            'Webpack',
            'Styled Components',
            'Storybook',
            'Monorepos',
            'Design systems'
        ],
        softSkills: [
            'Communication',
            'Collaboration',
            'Mentoring',
            'Independent work',
            'Problem-solving',
            'Initiative',
            'Usability focus',
            'Code quality advocacy',
            'Keeping up with new technologies'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Zinkworks',
        jobTitle: 'Senior React UI Developer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'React Class Components',
            'React Functional Components',
            'React Hooks',
            'HTML',
            'CSS',
            'Frontend architecture',
            'Performance optimization',
            'Accessibility',
            'Git',
            'Agile development',
            'Jira',
            'Confluence',
            'UI/UX design without UX support',
            'Data-heavy interfaces',
            'Docker',
            'CI/CD pipelines',
            'FlutterFlow',
            'Streamlit'
        ],
        softSkills: [
            'Ownership',
            'Autonomy',
            'Collaboration',
            'Communication',
            'Problem-solving',
            'Teamwork',
            'Adaptability',
            'High performance mindset',
            'Decision-making',
            'Working in distributed teams'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Monad Foundation',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'Next.js',
            'TypeScript',
            'Svelte',
            'SvelteKit',
            'Design systems',
            'Component libraries',
            'Tokens and theming',
            'Figma to production UI',
            'Animations',
            'Micro-interactions',
            'Framer Motion',
            'GSAP',
            'Accessibility',
            'ARIA',
            'Keyboard support',
            'Color contrast standards',
            'Responsive design',
            'Container queries',
            'CSS Grid',
            'Flexbox',
            'CSS custom properties',
            'Tailwind CSS',
            'shadcn/ui',
            'Performance optimization',
            'Bundle size optimization',
            'Code splitting',
            'Hydration strategies',
            'Caching strategies',
            'Virtualization',
            'React Query',
            'SWR',
            'Wallet integrations',
            'WalletConnect',
            'Injected providers',
            'On-chain data rendering',
            'RPC/indexer integration',
            'State management for loading/skeleton/error',
            'Testing best practices',
            'CI checks',
            'Documentation',
            'Git',
            'UI refactoring',
            'Playwright',
            'Testing Library',
            'Storybook',
            'Chromatic',
            'Visual regression testing',
            'Style Dictionary',
            'Performance tooling',
            'Lighthouse',
            'WebPageTest',
            'Perfetto',
            'Monitoring tools',
            'Sentry',
            'Datadog',
            'New Relic',
            'i18n',
            'RTL support',
            'WebGL',
            'Canvas',
            'SVG'
        ],
        softSkills: [
            'Ownership',
            'Autonomy',
            'Attention to detail',
            'Collaboration',
            'Communication',
            'Systems thinking',
            'Pragmatism',
            'Consistency',
            'Clear documentation',
            'Self-direction',
            'Feedback culture',
            'Quality mindset'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Restream',
        jobTitle: 'Senior Software Engineer - Frontend',
        workMode: 'Remote',
        yearsOfExperience: 0,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'React.js',
            'State management systems',
            'MobX',
            'CSS',
            'LESS',
            'SASS',
            'Node.js',
            'REST APIs',
            'Relational databases',
            'NoSQL databases',
            'AWS',
            'Linux',
            'Docker',
            'Kubernetes',
            'Continuous deployment'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Entrepreneurial attitude',
            'Attention to detail',
            'Design sensibility',
            'Analytical thinking',
            'Self-directed',
            'Teamwork',
            'User-focused mindset'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Confidential Global Software Company',
        jobTitle: 'Senior Frontend Developer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'HTML5',
            'CSS3',
            'React.js',
            'Angular',
            'Vue.js',
            'State management libraries',
            'RESTful APIs',
            'Webpack',
            'Vite',
            'Responsive design',
            'Web performance optimization',
            'UX best practices',
            'Git',
            'Agile development'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Leadership',
            'Mentorship',
            'Problem-solving',
            'Attention to detail',
            'Creativity',
            'Innovation',
            'Autonomy',
            'Teamwork'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Confidential Blockchain Startup',
        jobTitle: 'Senior Software Engineer - Web3 & Cross-Chain DApps',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'TypeScript',
            'React.js',
            'Next.js',
            'XState',
            'Wagmi',
            'React Native',
            'UI/UX design',
            'Frontend optimization',
            'SDK development',
            'Cross-chain DApps',
            'Blockchain technology',
            'DeFi platforms',
            'Observability',
            'Tracing',
            'State machines',
            'Mobile, tablet, and desktop frontend development',
            'Code quality',
            'Code maintainability'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Problem-solving',
            'Attention to detail',
            'UI/UX sensibility',
            'Autonomy',
            'Teamwork',
            'Cross-timezone collaboration',
            'Startup mindset'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Proxify',
        jobTitle: 'Senior Software Developer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'Next.js',
            'Node.js',
            'JavaScript (ES6+)',
            'TypeScript',
            'HTML5',
            'CSS3',
            'CSS-in-JS',
            'State management libraries',
            'Redux',
            'Zustand',
            'Recoil',
            'RESTful APIs',
            'Asynchronous operations',
            'Frontend-backend integration',
            'Unit testing',
            'Integration testing',
            'Jest',
            'React Testing Library',
            'Webpack',
            'Vite',
            'Performance optimization',
            'Accessibility',
            'CI/CD pipelines',
            'GraphQL',
            'gRPC',
            'Backend technologies',
            'Backend databases',
            'Cloud services',
            'Modular component design',
            'Design systems',
            'Component libraries'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Problem-solving',
            'Attention to detail',
            'Autonomy',
            'Teamwork',
            'Agile mindset',
            'Creativity',
            'User-focused mindset',
            'Fast-paced environment adaptability'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Intercom',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'JavaScript',
            'HTML',
            'CSS',
            'Node.js',
            'SaaS product development',
            'Frontend architecture',
            'Design systems',
            'Localization',
            'Build tooling',
            'Observability',
            'Unit testing',
            'Code reviews',
            'Design documentation',
            'Technical mentoring',
            'Performance optimization',
            'Reliability best practices'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Leadership',
            'Mentorship',
            'Problem-solving',
            'Autonomy',
            'Teamwork',
            'Attention to detail',
            'Technical articulation',
            'Persistence',
            'Learning agility'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Bentley Systems',
        jobTitle: 'Senior Software Engineer (TypeScript / JavaScript / React)',
        workMode: 'Hybrid',
        yearsOfExperience: 6,
        bachelorDegree: true,
        mastersDegree: true,
        hardSkills: [
            'TypeScript',
            'JavaScript',
            'React.js',
            'Node.js',
            'Unit testing',
            'Test-driven development',
            'Object-Oriented Programming (OOP)',
            'SOLID principles',
            'DRY principles',
            'Software design principles',
            'Software Development Life Cycle (SDLC)',
            'Agile / Scrum',
            'Git',
            'C++',
            'C#',
            '.NET',
            'Azure DevOps',
            'Backlog management',
            'Jira',
            'TFS',
            'ADO',
            'Software design diagrams',
            'Mathematical foundations (Geometry, Trigonometry)',
            'Infrastructure software knowledge'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Problem-solving',
            'Analytical thinking',
            'Attention to detail',
            'Ownership',
            'Mentorship',
            'Teamwork',
            'Continuous learning',
            'Adaptability'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Dataminr',
        jobTitle: 'Frontend Software Engineer III',
        workMode: 'Remote',
        yearsOfExperience: 4,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'JavaScript',
            'TypeScript',
            'React Hooks',
            'React Context',
            'React Suspense',
            'Concurrent React features',
            'State management',
            'TanStack Query',
            'Zustand',
            'Component libraries',
            'Design systems',
            'REST APIs',
            'GraphQL (queries, mutations, caching, fragments)',
            'Unit testing',
            'Jest',
            'Vitest',
            'Component testing',
            'Integration testing',
            'React Testing Library',
            'E2E testing',
            'Cypress',
            'Playwright',
            'Frontend architecture',
            'Performance optimization',
            'Modern frontend patterns'
        ],
        softSkills: [
            'Problem-solving',
            'Collaboration',
            'Communication',
            'Attention to detail',
            'Autonomy',
            'Teamwork',
            'Fast-paced environment adaptability',
            'Technical reasoning',
            'Feature delivery focus',
            'Learning agility'
        ]
    },
    {
        dateCreated: 1763830348000,
        companyName: 'Squarespace',
        jobTitle: 'Senior Frontend Engineer - International Team',
        workMode: 'Hybrid',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'TypeScript',
            'Frontend architecture',
            'Testing best practices',
            'Performance optimization',
            'Maintainable code',
            'Maintainable architecture',
            'Internationalization',
            'i18n',
            'Localization',
            'Translation workflows',
            'Component libraries',
            'Design systems',
            'Collaboration with designers',
            'Collaboration with product managers'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Mentorship',
            'Problem-solving',
            'Attention to detail',
            'Autonomy',
            'Teamwork',
            'Technical articulation',
            'Cross-disciplinary communication',
            'Inclusive mindset'
        ]
    },
    {
        dateCreated: 1763919427667,
        companyName: 'Canto',
        jobTitle: 'Senior Frontend Software Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'React Hooks',
            'React Context',
            'React Routing',
            'Component composition',
            'TypeScript',
            'JavaScript (ES6+)',
            'HTML',
            'CSS',
            'Tailwind CSS',
            'Material UI (MUI)',
            'TanStack Query',
            'Figma',
            'WCAG accessibility',
            'Frontend performance optimization',
            'Unit testing',
            'Jest',
            'React Testing Library',
            'Integration testing',
            'Component testing',
            'Playwright',
            'CI/CD practices',
            'Agile workflow'
        ],
        softSkills: [
            'Problem-solving',
            'Collaboration',
            'Communication',
            'Mentorship',
            'Teamwork',
            'Attention to detail',
            'Autonomy',
            'Creativity',
            'Adaptability',
            'Proactive learning'
        ]
    },
    {
        dateCreated: 1763919427667,
        companyName: 'Pragmatike',
        jobTitle: 'Senior/Lead Frontend Developer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: true,
        hardSkills: [
            'React.js',
            'Redux.js',
            'JavaScript (ES6+)',
            'TypeScript',
            'Node.js',
            'HTML5',
            'CSS3',
            'SPA development',
            'Reusable UI components',
            'Object-Oriented JavaScript',
            'Object-Oriented Programming',
            'Unit testing',
            'Performance optimization',
            'UI testing',
            'Selenium',
            'Front-end tooling',
            'ESLint',
            'Prettier',
            'Responsive design',
            'Micro Frontend Applications'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Problem-solving',
            'Mentorship',
            'Attention to detail',
            'Creativity',
            'Proactive learning',
            'Autonomy',
            'Teamwork',
            'Adaptability'
        ]
    },
    {
        dateCreated: 1763919427667,
        companyName: 'BrainRocket',
        jobTitle: 'Senior Angular Developer',
        workMode: 'On-site',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Angular 2+',
            'Angular 15',
            'TypeScript',
            'Web development',
            'REST APIs',
            'Jest',
            'Testing frameworks',
            'Test runner frameworks',
            'SOLID principles',
            'GRASP principles',
            'Client-side architecture',
            'Design patterns',
            'Cross-browser compatibility',
            'Performance optimization',
            'Git',
            'npm',
            'Webpack',
            'Babel',
            'Linters',
            'Nx framework',
            'TypeScript AST',
            'Code modifiers',
            'GitLab',
            'CI/CD',
            'Docker',
            'NGINX',
            'Node.js',
            'UX understanding'
        ],
        softSkills: [
            'Problem-solving',
            'Learning skills',
            'Ability to work independently',
            'Technical advice and mentorship',
            'Task coordination',
            'Communication',
            'Attention to detail',
            'Team collaboration',
            'Strong product mindset'
        ]
    },
    {
        dateCreated: 1764096000000,
        companyName: 'Tiger Data',
        jobTitle: 'Senior Front-End Engineer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'TypeScript',
            'React',
            'JavaScript',
            'UI/UX implementation',
            'Pixel-perfect UI',
            'Cypress',
            'testing',
            'End-to-end testing',
            'API development',
            'Backend API layer experience',
            'SQL',
            'Data-driven query languages',
            'SaaS product development',
            'Cloud services UI development',
            'Golang',
            'PostgreSQL',
            'Docker',
            'Kubernetes',
            'AWS',
            'Data visualization',
            'modern frameworks'
        ],
        softSkills: [
            'Ownership',
            'Self-driven execution',
            'Strong communication',
            'Attention to detail',
            'Collaboration',
            'Working with product and design',
            'Customer-centric thinking',
            'Ability to thrive in fast-paced environments',
            'Remote teamwork'
        ]
    },
    {
        dateCreated: 1764096000000,
        companyName: 'Primus Global Solutions',
        jobTitle: 'Senior Frontend Developer',
        workMode: 'Hybrid',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React',
            'Next.js',
            'TypeScript',
            'Vue',
            'AI-powered solutions',
            'Chatbots',
            'LLM workflows',
            'OpenAI GPT',
            'SSR',
            'SSG',
            'Component libraries',
            'Dashboards',
            'Accessibility',
            'ally',
            'Performance optimisation',
            'HTML5',
            'CSS3',
            'JavaScript/ES6+',
            'AngularJS',
            'Node.js',
            'MobX',
            'Redux',
            'Tailwind CSS',
            'MUI',
            'Styled Components',
            'WordPress',
            'Joomla',
            'Drupal',
            'Cockpit CMS',
            'Agile teamwork'
        ],
        softSkills: ['Agile teamwork']
    },
    {
        dateCreated: 1764096000000,
        companyName: 'Refurbed',
        jobTitle: 'Senior Frontend Engineer - Delivery & Returns',
        workMode: 'Remote',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Vue',
            'TypeScript',
            'modern JavaScript',
            'semantic HTML',
            'CSS',
            'responsive layout',
            'Core Web Vitals',
            'runtime performance',
            'accessibility',
            'state management',
            'routing',
            'modularization',
            'component library',
            'design system',
            'legacy code refactoring',
            'architectural improvements',
            'API collaboration'
        ],
        softSkills: ['communication', 'mentorship', 'collaboration']
    },
    {
        dateCreated: 1764096000000,
        companyName: 'Confidential UAE Startup',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'On-site',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: ['React.js', 'TypeScript', 'testing', 'large-scale applications'],
        softSkills: ['communication', 'confidence', 'collaboration']
    },
    {
        dateCreated: 1764096000000,
        companyName: 'Flywheel',
        jobTitle: 'Senior Frontend Engineer - Delivery & Returns',
        workMode: 'Hybrid',
        yearsOfExperience: 8,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'Angular (13+)',
            'TypeScript',
            'JavaScript (ES6+)',
            'State management libraries',
            'HTML5',
            'CSS3',
            'SASS',
            'RESTful APIs',
            'Responsive design',
            'UI/UX best practices',
            'Accessibility (WCAG)',
            'Front-end build tools',
            'Testing frameworks',
            'Jasmine',
            'Karma',
            'Cypress',
            'CI/CD pipelines',
            'Agile Project Management tools',
            'Jira',
            'Git',
            'Version control',
            'Design systems',
            'Refactoring',
            'Performance optimization'
        ],
        softSkills: [
            'Communication',
            'Collaboration',
            'Analytical thinking',
            'Problem-solving',
            'Mentorship',
            'Teamwork',
            'Autonomy'
        ]
    },
    {
        dateCreated: 1764091820000,
        companyName: 'Sitecore',
        jobTitle: 'Senior Frontend Developer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'React',
            'TypeScript',
            'Shadcn UI components',
            'Tailwind CSS',
            'Tanstack Router',
            'Tanstack libraries',
            'Vite',
            'Github',
            'Frontend build tools',
            'Code reviews',
            'Containerized application development',
            'AWS cloud services',
            'Automation testing',
            'Version control'
        ],
        softSkills: ['Problem-solving', 'Architectural decision-making', 'Collaboration', 'Leadership', 'Innovation']
    },
    {
        dateCreated: 1764091931000,
        companyName: 'ClickUp',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Angular 2+',
            'JavaScript',
            'TypeScript',
            'NgRx',
            'RxJS',
            'HTML',
            'CSS',
            'Reusable UI components',
            'State management',
            'Unit testing',
            'Integration testing',
            'Performance optimization',
            'Cross-browser compatibility',
            'Accessibility'
        ],
        softSkills: [
            'Problem-solving',
            'Self-starter',
            'Operational focus',
            'Collaboration',
            'Communication',
            'Mentorship'
        ]
    },
    {
        dateCreated: 1764092004000,
        companyName: 'Amazon Web Services (AWS)',
        jobTitle: 'Senior Frontend Development Engineer',
        workMode: 'On-site',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'HTML',
            'CSS',
            'JavaScript',
            'TypeScript',
            'Node.js',
            'React',
            'State management patterns',
            'RESTful APIs',
            'Modern build tools',
            'Webpack',
            'Vite',
            'AWS/cloud technologies',
            'Relational databases',
            'MySQL',
            'SQL querying tools'
        ],
        softSkills: [
            'Mentorship',
            'Technical leadership',
            'Problem-solving',
            'Collaboration',
            'Communication',
            'Curiosity',
            'Explorative mindset',
            'Attention to detail'
        ]
    },
    {
        dateCreated: 1764150193000,
        companyName: 'Remote',
        jobTitle: 'Senior Frontend Engineer (Website Team)',
        workMode: 'Remote',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Node.js',
            'React',
            'Next.js',
            'TypeScript',
            'JavaScript',
            'Semantic HTML',
            'CSS',
            'SEO best practices',
            'Web performance optimization',
            'Performance audits',
            'Third-party APIs',
            'Analytics integrations',
            'Headless CMS integrations',
            'Postgres (context)',
            'Elixir/Phoenix (context)',
            'CI/CD',
            'Gitlab',
            'AWS hosting'
        ],
        softSkills: [
            'Independent work',
            'Self-guidance',
            'Curiosity',
            'Willingness to learn',
            'Collaboration with Marketing and Sales',
            'Handling ambiguity',
            'Transforming abstract concepts into working software'
        ]
    },
    {
        dateCreated: 1764165165000,
        companyName: 'Kraken',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Software development',
            'Web applications',
            'JavaScript',
            'TypeScript',
            'React',
            'API design',
            'Security',
            'Performance optimization',
            'Next.js',
            'WebSockets',
            'Frontend testing frameworks',
            'Modern front-end build pipelines',
            'Modern front-end tooling',
            'UI/UX best practices',
            'Experience in large technology organizations',
            'Experience in fast growing startups',
            'Consumer payments experience',
            'Crypto applications experience',
            'Fintech mobile applications experience',
            'Scalable system design',
            'Maintainable system design',
            'Fault-tolerant system design',
            'Software architecture',
            'Design patterns'
        ],
        softSkills: [
            'Strong written communication',
            'Strong verbal communication',
            'Mentoring junior and senior engineers',
            'Providing constructive feedback',
            'Influencing technical decisions',
            'Contributing to technical strategy',
            'Leading complex initiatives',
            'Driving process improvements',
            'Collaboration across teams'
        ]
    },
    {
        dateCreated: 1764165254000,
        companyName: 'Lumenalta',
        jobTitle: 'Senior React Developer',
        workMode: 'Remote',
        yearsOfExperience: 7,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'JavaScript',
            'React',
            'Redux',
            'WebSockets',
            'Async/Await',
            'Clean code',
            'Testable code',
            'Well-documented code'
        ],
        softSkills: [
            'Problem solving',
            'Proactive',
            'Go-getter',
            'Team player',
            'Professional',
            'Empathic',
            'Advanced English fluency'
        ]
    },
    {
        dateCreated: 1764165459000,
        companyName: 'Yahoo',
        jobTitle: 'Principal Software Engineer',
        workMode: 'Remote',
        yearsOfExperience: 8,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'React',
            'Next.js',
            'Angular',
            'Ember',
            'Node.js',
            'HTML5',
            'CSS3',
            'AJAX',
            'Responsive web design',
            'Redux Toolkit',
            'Storybook',
            'Atomic CSS',
            'Superagent',
            'Web Vitals',
            'JSON',
            'REST APIs',
            'Test-driven development',
            'Jest',
            'Selenium',
            'WebdriverIO',
            'React Testing Library',
            'Mock Service Worker',
            'Playwright',
            'Web performance optimization',
            'Application stability',
            'Debugging large-scale web applications'
        ],
        softSkills: [
            'Collaboration with global teams',
            'Communication',
            'Professionalism',
            'Empathy',
            'Problem-solving',
            'Attention to detail',
            'Mentorship',
            'Continuous learning'
        ]
    },
    {
        dateCreated: 1764165542000,
        companyName: 'Solance',
        jobTitle: 'Senior UI Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React Native',
            'React',
            'UI & UX design',
            'Figma',
            'Figma to pixel-perfect implementation',
            'iOS development',
            'Android development',
            'Web development',
            'Multi-channel deployment',
            'MFA implementation',
            'SSO',
            'Offline-first applications',
            'Local storage',
            'Deep linking',
            'Notifications',
            'Accessibility',
            'Internationalization',
            'Atomic design',
            'UI testing',
            'UI code deployment',
            'Release management',
            'Observability',
            'User behavior tracking',
            'Alerting principles',
            'DevOps/SRE automation for UI deployments',
            'AI tooling',
            'Visual design',
            'Cross-channel UI frameworks'
        ],
        softSkills: [
            'Mentorship',
            'Collaboration with business and product teams',
            'Agile software development',
            'Business analysis',
            'Scrum Master skills',
            'Problem-solving',
            'Proactive automation mindset',
            'Team leadership',
            'Attention to detail',
            'Customer-centric thinking'
        ]
    },
    {
        dateCreated: 1764165762000,
        companyName: 'BeyondBMI',
        jobTitle: 'Senior Frontend Software Engineer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React Native',
            'Next.js',
            'Storybook',
            'React Router',
            'JavaScript',
            'RESTful APIs',
            'State management',
            'Zustand',
            'Jest',
            'Unit testing',
            'Automated testing',
            'Version control',
            'Frontend architecture',
            'Clean code',
            'Maintainable code',
            'Reusable code'
        ],
        softSkills: [
            'Collaboration',
            'Autonomy',
            'Attention to detail',
            'Methodical work process',
            'Coaching and mentoring',
            'Code reviews',
            'Problem-solving',
            'Continuous learning',
            'Technical innovation',
            'Creativity in solutions',
            'Proactivity',
            'Challenging the norm'
        ]
    },
    {
        dateCreated: 1764165848000,
        companyName: 'Datavant',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'TypeScript',
            'JavaScript',
            'React',
            'Vue',
            'Angular',
            'HTML',
            'CSS',
            'Responsive design',
            'Accessibility (WCAG)',
            'Design systems',
            'Component libraries',
            'Unit testing',
            'End-to-end testing',
            'Jest',
            'Testing Library',
            'Cypress',
            'Frontend migrations',
            'Greenfield development',
            'modular code',
            'maintainable code',
            'Python',
            'Spark',
            'Snowflake',
            'AWS',
            'Azure'
        ],
        softSkills: [
            'Collaboration with product designers and backend engineers',
            'Cross-functional teamwork',
            'Mentoring and coaching',
            'Ownership of projects',
            'Self-motivation',
            'Adaptability',
            'Problem-solving',
            'Attention to detail',
            'Technical excellence',
            'Communication skills',
            'Passion for healthcare and impact-driven work'
        ]
    },
    {
        dateCreated: 1764165955000,
        companyName: 'Centripetal Networks',
        jobTitle: 'Software UI Engineer, CIS Cloud Services',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: true,
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'React',
            'Material UI',
            'Storybook',
            'SPA development',
            'PWA',
            'Web Workers',
            'Web Sockets',
            'RESTful Services',
            'GraphQL',
            'CQRS',
            'CI/CD',
            'DevOps',
            'SecDevOps',
            'UX process',
            'Frontend development',
            'Backend integration',
            'Efficient data handling'
        ],
        softSkills: [
            'Collaborative problem-solving',
            'Ownership and impact',
            'Continuous self-improvement',
            'Innovation mindset',
            'Customer-focused development',
            'Communication skills',
            'Adaptability',
            'Team collaboration'
        ]
    },
    {
        dateCreated: 1764166076000,
        companyName: 'Jibble Group',
        jobTitle: 'Senior Frontend Developer (Vue.js)',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Vue.js',
            'Vue 3',
            'Vue Composition API',
            'JavaScript',
            'TypeScript',
            'Material Design',
            'Vuetify',
            'Frontend web development',
            'Pixel-perfect UI implementation',
            'Unit testing',
            'Web client development',
            'Refactoring',
            'Agile',
            'Scrum'
        ],
        softSkills: [
            'Collaboration with product managers and designers',
            'Code review and mentoring',
            'Continuous learning',
            'Attention to detail',
            'Remote teamwork',
            'Communication skills',
            'Adaptability',
            'Problem-solving'
        ]
    },
    {
        dateCreated: 1764166161000,
        companyName: 'LimeFlight',
        jobTitle: 'Senior Frontend Engineer (Angular)',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'Angular 20',
            'RxJS',
            'Signals',
            'NgRx',
            'JavaScript',
            'TypeScript',
            'Unit testing',
            'Karma',
            'Jasmine',
            'Integration testing',
            'Cypress',
            'Playwright',
            'GitHub Actions',
            'Frontend architecture',
            'Component library management',
            'Figma',
            'Storybook',
            'Design Systems',
            'Reactive programming',
            'UI/UX development',
            'Reusable code design'
        ],
        softSkills: [
            'Collaboration with designers, product managers, and backend engineers',
            'Problem-solving',
            'Continuous learning',
            'Ability to explain trade-offs to non-technical stakeholders',
            'Attention to maintainability and quality',
            'Communication skills',
            'Adaptability',
            'Team-oriented mindset'
        ]
    },
    {
        dateCreated: 1764166253000,
        companyName: 'Apata',
        jobTitle: 'Senior Frontend Developer',
        workMode: 'On-site',
        yearsOfExperience: 4,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'JavaScript (ES6+)',
            'TypeScript',
            'HTML',
            'CSS',
            'UI/UX implementation',
            'Frontend optimization',
            'Responsive design',
            'Browser testing',
            'Debugging',
            'Performance optimization',
            'Build tools',
            'Web development lifecycle',
            'Component-based architecture',
            'Technical documentation'
        ],
        softSkills: [
            'Collaboration with backend engineers and designers',
            'Detail-oriented',
            'Self-motivated',
            'Positive mindset',
            'Problem-solving',
            'Adaptability',
            'User-focused development',
            'Team player'
        ]
    },
    {
        dateCreated: 1764166376000,
        companyName: 'NETGEAR',
        jobTitle: 'Senior Software Engineer (Web)',
        workMode: 'Hybrid',
        yearsOfExperience: 8,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'React.js',
            'Vue.js',
            'JavaScript',
            'Node.js',
            'Java',
            'Python',
            'TypeScript',
            'SPA development',
            'PWA development',
            'Frontend architecture',
            'Cententful',
            'Contentstack',
            'Kentico',
            'CMS',
            'Agile development',
            'Web performance optimization',
            'SEO compliance',
            'Integration of third-party services',
            'Technical leadership',
            'Code review',
            'Code mentorship'
        ],
        softSkills: [
            'Collaboration with cross-functional teams',
            'Communication',
            'Proactive problem-solving',
            'Resourcefulness',
            'Mentorship',
            'Teamwork',
            'Strategic thinking',
            'Adaptability in fast-paced environments'
        ]
    },
    {
        dateCreated: 1764166464000,
        companyName: 'Henry Schein, Inc.',
        jobTitle: 'Sr Front-End Developer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'Angular (v8+)',
            'TypeScript',
            'HTML5',
            'CSS3',
            'SCSS',
            'Responsive web design',
            'Next.js',
            'Sitecore JSS',
            'RESTful APIs',
            'GraphQL',
            'Web Sockets',
            'Git',
            'CI/CD pipelines',
            'Webpack',
            'Nx',
            'SSR',
            'SSG',
            'ISR',
            'Performance profiling',
            'Lazy loading',
            'Code splitting',
            'Accessibility (WCAG)',
            'SEO optimization',
            'Cypress',
            'Jest',
            'Playwright',
            'Testing frameworks'
        ],
        softSkills: [
            'Collaboration with cross-functional teams',
            'Problem-solving',
            'Attention to detail',
            'Professional behavior',
            'Mentorship',
            'Adaptability',
            'Strong communication'
        ]
    },
    {
        dateCreated: 1764166693000,
        companyName: 'epilot',
        jobTitle: 'Senior Product Engineer (Frontend)',
        workMode: 'Remote',
        yearsOfExperience: 4,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'JavaScript (ES6+)',
            'Hooks',
            'state management',
            'routing',
            'React',
            'TypeScript',
            'Webpack',
            'ESLint',
            'Unit testing',
            'end-to-end testing',
            'HTML',
            'CSS',
            'GraphQL',
            'Node.js',
            'AWS',
            'Microfrontends',
            'Serverless architectures',
            'Developer tooling',
            'Developer automation'
        ],
        softSkills: [
            'Collaboration in cross-functional teams',
            'Product mindset',
            'Problem-solving',
            'Agile methodology',
            'User-focused development',
            'Ownership & accountability',
            'Continuous learning'
        ]
    },
    {
        dateCreated: 1764166868000,
        companyName: 'Swissblock',
        jobTitle: 'Full Stack Software Engineer (UI)',
        workMode: 'Remote',
        yearsOfExperience: 3,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React',
            'Node.js',
            'TypeScript',
            'CSS',
            'GraphQL',
            'Docker',
            'Containerized environments',
            'Secure web application development',
            'D3.js',
            'visx',
            'Data visualization',
            'Node.js',
            'Kubernetes deployment',
            'Cloud platforms',
            'GCP'
        ],
        softSkills: [
            'Collaboration with business and technical stakeholders',
            'Problem-solving and analytical thinking',
            'User-focused interface design',
            'Team player',
            'Sense for quality and reliability',
            'Curiosity and willingness to learn',
            'Strong English communication'
        ]
    },
    {
        dateCreated: 1764167015000,
        companyName: 'Mastercard',
        jobTitle: 'Senior Software Engineer (Angular UI Dev)',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        hardSkills: [
            'Angular',
            'Java',
            'Sprint Boot',
            'Spring Batch',
            'Hibernate',
            'JPA',
            'Full-stack development',
            'Oracle Database',
            'SQL',
            'PL',
            'SOAP',
            'RESTful APIs',
            'CI/CD tools',
            'Jenkins',
            'Maven',
            'Gradle',
            'Unix scripts',
            'Shell scripts',
            'Build',
            'Scripting',
            'Cypress',
            'Selenium',
            'Rest-Assured',
            'TestNG',
            'Postman',
            'Insomnia',
            'Test automation frameworks',
            'PCF',
            'AWS',
            'Cloud-native development',
            'Github copilot',
            'AI-assisted development tools',
            'Microservices design patterns'
        ],
        softSkills: [
            'Mentoring and supporting team growth',
            'Collaboration in cross-functional Agile teams',
            'Problem-solving and innovation',
            'Strong communication skills',
            'Adaptability to new technologies',
            'Ability to multitask and meet deadlines',
            'Attention to security and corporate compliance'
        ]
    },
    {
        dateCreated: 1764352131000,
        companyName: 'Welltech',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'Frontend application development',
            'JavaScript (ES6+)',
            'TypeScript 5+',
            'React 18+',
            'React-Query',
            'Redux Saga',
            'Styled Components',
            'Vite',
            'RESTful API integration',
            'Web security',
            'Responsive UX patterns',
            'Software design principles',
            'solid',
            'Design patterns',
            'Testing strategies',
            'Sentry',
            'Datadog',
            'A/B testing',
            'multivariate testing',
            'Material UI',
            'Next.js',
            'SSR',
            'Webpack configuration',
            'Vite configuration'
        ],
        softSkills: [
            'Strong communication (English C1)',
            'Collaboration with cross-functional teams',
            'Mentoring',
            'Leading technical discussions',
            'Ownership and accountability',
            'Strategic thinking',
            'Continuous learning mindset',
            'Ability to translate business requirements into technical solutions'
        ]
    },
    {
        dateCreated: 1764352226000,
        companyName: 'Surfe',
        jobTitle: 'Lead Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: 8,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React',
            'TypeScript',
            'API development understanding',
            'UI components',
            'UX implementation',
            'Monitoring tools',
            'Datadog',
            'Chrome extension development',
            'Golang',
            'CI/CD principles',
            'DevOps knowledge',
            'Tailwind',
            'Linear',
            'Notion',
            'Slack',
            'Figma',
            'Google Suite'
        ],
        softSkills: [
            'High energy mindset',
            'Action-oriented attitude',
            'Ownership',
            'Mentoring',
            'Collaboration with product, design, backend',
            'Reflexivity',
            'Continuous improvement mindset',
            'Communication skills',
            'Comfortable with uncertainty',
            'Team culture contribution (trust, respect, transparency)'
        ]
    },
    {
        dateCreated: 1764352451000,
        companyName: 'OpenVpn Inc.',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        hardSkills: [
            'React 19',
            'TypeScript 5.9',
            'Redux Toolkit',
            'RTK Query',
            'Rsbuild',
            'Rspack',
            'RESTful API integration',
            'Server-Sent Events',
            'SSE',
            'Message streaming',
            'Real-time features',
            'Vanilla Extract',
            'Tailwind',
            'CSS 4',
            'HeroUI',
            'NextUI',
            'React Hook Form',
            'Valibot',
            'React Router 7',
            'Vitest',
            'React Testing Library',
            'Vite',
            'Webpack',
            'AI-assisted development',
            'Claude code',
            'Biome',
            'SonarQube',
            'Sentry',
            'Git workflows',
            'Debugging performance issues'
        ],
        softSkills: [
            'Cross-functional collaboration',
            'Problem solving',
            'Architectural thinking',
            'Writing clean, testable code',
            'Willingness to adopt AI tools',
            'Staying current with new technologies'
        ]
    },
    {
        dateCreated: 1764413099000,
        companyName: 'Attio',
        jobTitle: 'Senior Product Engineer',
        workMode: 'Remote',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: [95000, 125000],
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'React',
            'Zod',
            'Lexical',
            'Frontend development',
            'Building modern web applications',
            'Building modern desktop applications',
            'Client-side state management',
            'Handling real-time data',
            'Collaborative editing'
        ],
        softSkills: [
            'UI and product sense',
            'Project ownership',
            'Problem solving',
            'Proactive attitude',
            'Communication with cross-functional teams',
            'Interest in innovation and experimentation',
            'Mentoring'
        ]
    },
    {
        dateCreated: 1764413219000,
        companyName: 'NUACOM',
        jobTitle: 'Senior React Application Developer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'JavaScript (ES6+)',
            'HTML5',
            'CSS3',
            'ReactJS',
            'React Native',
            'Redux',
            'TypeScript',
            'CI/CD pipelines',
            'Unit testing',
            'Integration testing',
            'Automated testing',
            'Git',
            'WebRTC',
            'EC2',
            'S3',
            'CloudFront',
            'ECS',
            'AWS'
        ],
        softSkills: [
            'Collaboration with cross-functional teams',
            'Clean code practices',
            'Performance optimization',
            'Debugging',
            'Problem solving',
            'Code review participation',
            'Continuous learning'
        ]
    },
    {
        dateCreated: 1764426060000,
        companyName: 'Smart Working',
        jobTitle: 'Frontend-Heavy Full Stack Developer (React + WordPress)',
        workMode: 'Remote',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'React',
            'Next.js',
            'JavaScript (ES6+)',
            'HTML5',
            'CSS3',
            'TailwindCSS',
            'WordPress',
            'PHP',
            'Custom WordPress theme development',
            'Custom WordPress plugin development',
            'CMS architecture',
            'Git',
            'GitHub',
            'API integrations',
            'HubSpot',
            'GA4',
            'Tracking tools',
            'Analytics tools',
            'AI-assisted development tools'
        ],
        softSkills: [
            'Communication',
            'Collaboration',
            'Working in cross-functional teams',
            'Ability to translate ideas into digital experiences',
            'Problem solving'
        ]
    },
    {
        dateCreated: 1764426325000,
        companyName: 'Sumsub',
        jobTitle: 'Web Development Team Lead',
        workMode: 'Remote',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'React',
            'Next.js',
            'Astro',
            'Redis',
            'Frontend development',
            'Web performance optimization',
            'SEO principles',
            'Animations',
            'interactive experiences',
            'DevOps tools',
            'CI/CD',
            'APIs',
            'Cloud hosting',
            'System architecture',
            'Code review'
        ],
        softSkills: [
            'Team leadership',
            'Leadership',
            'Mentorship',
            'Mentoring',
            'Communication',
            'Collaboration',
            'Proactive mindset',
            'Problem solving',
            'Cross-functional teamwork',
            'Creativity',
            'Growth and experimentation mindset'
        ]
    },
    {
        dateCreated: 1764521050000,
        companyName: 'Cytora',
        jobTitle: 'Senior Front End Engineer',
        workMode: 'Remote',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'React',
            'Redux',
            'Frontend development',
            'Full-stack development',
            'Functional programming',
            'Design patterns',
            'Singleton pattern',
            'API integration',
            '3rd party SDK integration',
            'UX collaboration',
            'Contract design',
            'Agile methodologies',
            'Web application development'
        ],
        softSkills: [
            'Teamwork',
            'Collaboration',
            'Communication',
            'Stakeholder management',
            'Attention to detail',
            'User empathy',
            'Autonomy',
            'Problem solving',
            'Culture building',
            'Proactive mindset',
            'Gap identification',
            'Risk communication'
        ]
    },
    {
        dateCreated: 1764521155000,
        companyName: 'Keyrock',
        jobTitle: 'Senior Full Stack Web Engineer',
        workMode: 'Remote',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'Full-stack development',
            'Frontend development',
            'Backend development',
            'UI/UX design',
            'Vue',
            'React',
            'Shadcn',
            'Rust',
            'Typed backend languages',
            'RESTful API design',
            'HTTP',
            'Performance optimisation',
            'Database design',
            'SQL',
            'NoSQL',
            'Schema design',
            'Query optimisation',
            'Git',
            'CI/CD',
            'Automated testing',
            'Debugging',
            'Profiling',
            'System tuning',
            'Documentation',
            'WebAssembly',
            'Modern API frameworks',
            'Secure coding',
            'OAuth2',
            'OpenID Connect',
            'D3.js',
            'Recharts',
            'Grafana',
            'Prometheus',
            'Loki',
            'Faro',
            'Datadog',
            'Kubernetes',
            'Containerisation',
            'Helm',
            'GitLab CI',
            'Infrastructure as Code',
            'Cloud technologies',
            'AWS',
            'GCP',
            'Azure',
            'Telemetry',
            'Observability'
        ],
        softSkills: [
            'Collaboration',
            'Communication',
            'Problem solving',
            'Analytical thinking',
            'Product mindset',
            'Ownership',
            'Mentorship',
            'Team contribution',
            'Proactive attitude',
            'Creativity',
            'Self-awareness'
        ]
    },
    {
        dateCreated: 1764521548000,
        companyName: 'MongoDB',
        jobTitle: 'Senior Software Development Engineer - Web Experiences',
        workMode: 'Hybrid',
        yearsOfExperience: 7,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'Javascript',
            'Typescript',
            'Next.js',
            'React',
            'Express',
            'Node.js',
            'CI/CD',
            'Drone',
            'GitHub',
            'AWS',
            'Docker',
            'Kubernetes',
            'Application monitoring',
            'Headless CMS',
            'Contentstack',
            'System architecture',
            'Technical specification writing',
            'Code review',
            'Technical documentation',
            'Agile',
            'SCRUM',
            'Jira',
            'SEO',
            'Analytics',
            'CMS migrations',
            'UI/UX best practices',
            'On-call rotation',
            'AI coding tools'
        ],
        softSkills: [
            'Technical leadership',
            'Cross-functional collaboration',
            'Mentorship',
            'Problem-solving',
            'Communication',
            'Planning',
            'Ownership',
            'Working in fast-paced environments',
            'Working with globally distributed teams'
        ]
    },
    {
        dateCreated: 1764521624000,
        companyName: 'SIROC',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: null,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'UX validation',
            'UI validation',
            'Responsive UI development',
            'SolidJS',
            'ReactJS',
            'TypeScript',
            'JavaScript',
            'REST APIs',
            'Version control',
            'Deployment pipelines',
            'Scalable architecture',
            'Maintainable architecture',
            'Frontend automation testing',
            'Unit testing',
            'End-to-end testing',
            'Functional testing',
            'Acceptance testing',
            'Code quality tools',
            'Clean code',
            'Code reviews',
            'Software architecture',
            'Domain-driven design (DDD)',
            'CQRS',
            'Hexagonal architecture',
            'npm',
            'Node.js ecosystem',
            'HTML',
            'CSS',
            'Docker',
            'Agile',
            'Integration testing'
        ],
        softSkills: [
            'Communication',
            'Motivating others',
            'Encouraging teammates',
            'Collaboration',
            'Persuasion',
            'Reducing team tension',
            'Prioritization',
            'Organization',
            'Working under pressure',
            'Proactive engagement'
        ]
    },
    {
        dateCreated: 1764521624000,
        companyName: 'Jobgether (for Partner Company)',
        jobTitle: 'Contract Senior Software Engineer (React/Node)',
        workMode: 'Remote',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: 125000,
        hardSkills: [
            'React',
            'Node.js',
            'Full-stack development',
            'Component architecture',
            'State management',
            'Redux',
            'MobX',
            'Context API',
            'Design systems',
            'Figma',
            'Figma API',
            'CSS',
            'Tailwind CSS',
            'CSS-in-JS',
            'CSS Modules',
            'TypeScript',
            'Modern JavaScript',
            'Transpiling',
            'Bundling',
            'esbuild',
            'Vite',
            'Yarn',
            'Turborepo',
            'Linting',
            'Formatting',
            'Reusable modules',
            'CI/CD',
            'Infrastructure as Code',
            'Automation',
            'Unit testing',
            'Integration testing',
            'End-to-end testing',
            'Visual regression testing',
            'Documentation generation',
            'Remote collaboration',
            'Agile'
        ],
        softSkills: [
            'Communication',
            'Explaining technical concepts',
            'Collaboration',
            'Proactive mindset',
            'Self-motivation',
            'Detail orientation',
            'Problem-solving',
            'Working efficiently in remote teams'
        ]
    },
    {
        dateCreated: 1764599884000,
        companyName: 'deskbird',
        jobTitle: 'Senior Full-Stack Engineer (Frontend-Focused)',
        workMode: 'Remote',
        yearsOfExperience: 6,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'Angular',
            'TypeScript',
            'RxJS',
            'Frontend Engineering',
            'Reusable Components',
            'Design Systems',
            'Storybook',
            'Node.js',
            'REST APIs',
            'API Design',
            'Backend Development',
            'Web Architecture',
            'Performance Optimization',
            'Web Accessibility',
            'Data Analysis',
            'User Behavior Analysis',
            'Third-Party Integrations',
            'Analytics Integrations',
            'Sales Automation Tools',
            'Data Tracking',
            'HubSpot',
            'Mixpanel',
            'Jimo',
            'AI-Assisted Development Tools',
            'GitHub Copilot',
            'Cursor',
            'Windsurf',
            'CI/CD',
            'GitHub Actions',
            'GCP'
        ],
        softSkills: [
            'Problem-Solving',
            'Curiosity',
            'Data-Driven Thinking',
            'Collaboration',
            'Cross-Functional Communication',
            'Coaching',
            'Mentoring',
            'Iterative Development',
            'User-Centric Thinking',
            'Leadership',
            'Architectural Decision-Making'
        ]
    },

    {
        dateCreated: 1764779666000,
        companyName: 'Venture Up',
        jobTitle: 'Staff Frontend Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 8,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'TypeScript',
            'JavaScript (ES6+)',
            'ReactJS',
            'Zustand',
            'TailwindCSS',
            'Vite',
            'Server-Side Rendering',
            'SSR',
            'AWS',
            'Performance optimization',
            'CI/CD',
            'AWS',
            'Kubernetes',
            'Cloud infrastructure',
            'Large-scale app architecture',
            'A/B testing',
            'E-commerce metrics',
            'LLMs'
        ],
        softSkills: [
            'Leadership across multiple teams',
            'Technical vision and strategy',
            'Mentorship of senior developers',
            'Collaboration with Engineering Managers and stakeholders',
            'Problem-solving in high-scale environments',
            'Innovation mindset',
            'Communication and influence'
        ]
    },
    {
        dateCreated: 1764779974000,
        companyName: 'Fenergo',
        jobTitle: 'Senior React Engineer',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'React',
            'TypeScript',
            'JavaScript (ES6+)',
            'CSS',
            'Material-UI',
            'CSS-in-JS libraries',
            'Jest',
            'React Testing Library',
            'Unit testing',
            'Cypress',
            'Integration testing',
            'Agile methodologies',
            'Library development',
            'Reusable component',
            'clean code',
            'scalable code',
            'code quality',
            'documentation',
            'code quality practices'
        ],
        softSkills: [
            'Collaboration with UX/UI designers, backend engineers, and product owners',
            'Autonomy and ownership',
            'Problem-solving',
            'High-quality standards',
            'Strong communication skills',
            'Curiosity and lifelong learning',
            'Cross-functional teamwork',
            'Impact-driven mindset'
        ]
    },
    {
        dateCreated: 1764780299000,
        companyName: 'Wayflyer',
        jobTitle: 'Frontend Engineer | (Dmitri note: 5 years plus)',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'TypeScript',
            'React',
            'HTML5',
            'CSS3',
            'JavaScript fundamentals',
            'RESTful API design',
            'RESTful API integration',
            'Python',
            'Django',
            'State management',
            'CI/CD pipelines',
            'Testing practices',
            'Performance optimization',
            'Reusable component development',
            'Frontend architecture'
        ],
        softSkills: [
            'Technical leadership and mentorship',
            'Collaboration with product and design teams',
            'Stakeholder management',
            'Proactive problem-solving',
            'Autonomy and ownership',
            'Communication of technical concepts to non-technical audiences',
            'Continuous learning and knowledge sharing',
            'Cross-functional teamwork',
            'High-quality standards',
            'Impact-driven mindset'
        ]
    },
    {
        dateCreated: 1764780577000,
        companyName: 'CorpGlobal Consulting',
        jobTitle: 'Frontend Developer | (Dmitri note: 5 years plus)',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'HTML5',
            'CSS3',
            'JavaScript',
            'ASP.NET MVC',
            'ASP.NET Webpages',
            'npm',
            'SQL',
            'DevOps',
            'GitHub',
            'Version control',
            'API integration',
            'LMS content creation',
            'Articulate Rise',
            'Adobe Suite',
            'UI/UX design',
            'E-learning storyboard design',
            'COTS software integration',
            'code maintenance',
            'Debugging'
        ],
        softSkills: [
            'Collaboration with instructors and technical teams',
            'Communication skills',
            'Remote work adaptability',
            'Problem-solving',
            'Attention to detail',
            'Time management',
            'Proactive and self-directed',
            'Team player mindset'
        ]
    },
    {
        dateCreated: 1764780747000,
        companyName: 'IBM',
        jobTitle: 'Software Developer - Web Developer | (Dmitri note: 5 years plus)',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: true,
        compensationRange: null,
        hardSkills: [
            'HTML5',
            'CSS3',
            'JavaScript (ES6+)',
            'TypeScript',
            'HTMX',
            'Alpine.js',
            'Tailwind CSS',
            'Bootstrap',
            'Responsive design',
            'Mobile-first development',
            'SSR',
            'Server-side rendering',
            'Jinja2 templates',
            'Django templates',
            'Vanilla JavaScript',
            'DOM manipulation',
            'SSE',
            'WebSocket',
            'Real-time dashboards',
            'Chart.js',
            'D3.js',
            'Recharts',
            'ApexCharts',
            'Charting libraries',
            'REST API integration',
            'Apollo',
            'URQL',
            'GraphQL clients',
            'Playwright',
            'Cypress',
            'Selenium',
            'WCAG',
            'ARIA',
            'Accessibility',
            'Cross-browser testing',
            'Frontend build tools',
            'Vite',
            'esbuild',
            'Rollup',
            'CSS preprocessors',
            'Sass',
            'PostCSS',
            'Version control',
            'git',
            'ESLint',
            'Prettier',
            'Stylelint',
            'linters',
            'formatters',
            'CI/CD for frontend',
            'Package managers',
            'npm',
            'yarn',
            'pnpm',
            'Turborepo',
            'Nx',
            'Frontend security',
            'XSS',
            'CSRF',
            'CSP',
            'secure headers'
        ],
        softSkills: [
            'Collaboration with cross-functional teams',
            'Problem-solving',
            'Attention to detail',
            'Ownership and responsibility',
            'Communication skills',
            'Proactive learning',
            'Translating designs into pixel-perfect implementations',
            'Mentorship and guidance',
            'High-quality standards',
            'Adaptability to new UI patterns and technologies'
        ]
    },
    {
        dateCreated: 1764780899000,
        companyName: 'formX',
        jobTitle: 'Frontend Engineer - 3D | (Dmitri note: 5 years plus)',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'React',
            'Redux',
            'JavaScript',
            'TypeScript',
            'Three.js',
            'WebGL frameworks',
            'Frontend architecture',
            'State management',
            '3D rendering and visualization',
            'Performance optimization',
            'Reusable component development',
            'UI/UX design'
        ],
        softSkills: [
            'Collaboration with designers, engineers, and founders',
            'Attention to visual detail',
            'Design sensibility',
            'Problem-solving',
            'Fast-paced startup adaptability',
            'Communication skills',
            'Ownership and initiative',
            'Cross-functional teamwork',
            'Creative thinking',
            'Impact-driven mindset'
        ]
    },
    {
        dateCreated: 1764781115000,
        companyName: 'Rush Street Interactive',
        jobTitle: 'Senior Frontend Platform Engineer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'JavaScript',
            'TypeScript',
            'React',
            'Vue',
            'Angular',
            'Vite',
            'Nx',
            'Webpack',
            'Rollup',
            'GitHub Actions',
            'GitLab CI',
            'Jenkins',
            'CI/CD systems',
            'Frontend monorepo management',
            'Debugging',
            'performance optimization',
            'Containerization',
            'Docker',
            'Kubernetes',
            'Cloud infrastructure',
            'AWS',
            'GCP',
            'Internal developer tooling',
            'Automation solutions',
            'Lighthouse CI',
            'Storybook',
            'Static asset analysis'
        ],
        softSkills: [
            'Collaboration with cross-functional teams',
            'Problem-solving',
            'Developer enablement and mentorship',
            'Proactive and methodical mindset',
            'Communication skills',
            'Operational excellence',
            'Ownership and accountability',
            'Continuous improvement',
            'Adaptability to evolving tooling',
            'Impact-driven mindset'
        ]
    },
    {
        dateCreated: 1764781221000,
        companyName: 'Block Labs',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'React',
            'JavaScript',
            'TypeScript',
            'Micro frontend architectures',
            'Build tools',
            'Bun',
            'Vite',
            'Webpack',
            'Cypress',
            'Selenium',
            'Testing frameworks',
            'CI/CD pipelines',
            'DevOps practices',
            'Containerization',
            'Cloud environments',
            'API integration',
            'UI/UX optimization',
            'Cross-browser compatibility',
            'Accessibility'
        ],
        softSkills: [
            'Collaboration with cross-functional teams',
            'Attention to performance and responsiveness',
            'Code quality and maintainability',
            'Problem-solving',
            'Communication skills',
            'Ownership and initiative',
            'User experience focus',
            'Mission-driven mindset',
            'Low-ego and mature work culture',
            'Adaptability and learning'
        ]
    },
    {
        dateCreated: 1764781334000,
        companyName: 'Arista Networks',
        jobTitle: 'Front-End Software Engineer - Ireland | (Dmitri note: 5 years plus)',
        workMode: 'On-site',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'JavaScript',
            'React',
            'Redux',
            'NodeJS',
            'ES6',
            'Webpack',
            'Storybook',
            'TypeScript',
            'Less',
            'CI/CD',
            'Frontend visualization UI',
            'Frontend telemetry UI',
            'Component design',
            'conversion from wireframes',
            'Performance optimization'
        ],
        softSkills: [
            'Collaboration with cross-functional teams',
            'Problem-solving',
            'Adaptability to change',
            'Attention to quality and reliability',
            'Ownership and initiative',
            'Communication skills',
            'User experience focus',
            'Curiosity and continuous learning',
            'Appreciation for engineering culture'
        ]
    },
    {
        dateCreated: 1764839810000,
        companyName: 'CoinsPaid',
        jobTitle: 'Frontend Engineer (Design core team) | (Dmitri note: 5 years plus)',
        workMode: 'Remote',
        yearsOfExperience: 4,
        bachelorDegree: null,
        mastersDegree: null,
        compensationRange: null,
        hardSkills: [
            'JavaScript',
            'React 18+',
            'HTML',
            'CSS',
            'Material UI',
            'Responsive web development',
            'Cross-browser compatibility',
            'Client-side performance optimization',
            'ES6',
            'ES7',
            'UI component development',
            'UI design system development',
            'Unit testing',
            'UI testing',
            'Integration testing',
            'Component testing',
            'Agile methodology'
        ],
        softSkills: [
            'Proactivity',
            'Ownership and responsibility',
            'Problem-solving',
            'Ability to work independently',
            'Collaboration with design and engineering teams',
            'Communication skills (English and Russian)'
        ]
    },
    {
        dateCreated: 1764839897000,
        companyName: 'Calyptus',
        jobTitle: 'Frontend Engineer | Unknown if Senior or Mid',
        workMode: 'Remote',
        yearsOfExperience: null,
        bachelorDegree: null,
        mastersDegree: null,
        compensationRange: null,
        hardSkills: [
            'HTML',
            'CSS',
            'TypeScript',
            'React',
            'Web3 development',
            'EVM blockchain interaction',
            'wagmi',
            'ethers.js',
            'dApp',
            'dApp development',
            'Decentralized application development',
            'Responsive dashboards',
            'Data visualization',
            'State management',
            'Real-time data handling',
            'Cross-chain transaction flows',
            'Frontend build tools',
            'Deployment pipelines',
            'Linux',
            'Command-line development',
            'API design',
            'Server-side fundamentals'
        ],
        softSkills: [
            'High ownership',
            'Adaptability',
            'Works well under pressure',
            'Strong communication',
            'Proactive problem-solving',
            'Collaboration with product/design/backend teams'
        ]
    },
    {
        dateCreated: 1764840097000,
        companyName: 'Workhuman',
        jobTitle: 'Software Engineer (React) | (Dmitri note: 5 years plus)',
        workMode: 'Hybrid',
        yearsOfExperience: 4,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'React',
            'JavaScript',
            'TypeScript',
            'Modern web application development',
            'UI performance optimization',
            'Maintainable UI architecture',
            'Accessibility best practices',
            'RESTful APIs',
            'Python (exposure)',
            'PostgreSQL',
            'SQL',
            'Redis',
            'AWS',
            'AWS ECS Fargate',
            'AWS Lambda',
            'AWS S3',
            'AWS RDS',
            'AWS Neptune',
            'AWS CloudFront',
            'AWS ALB',
            'Terraform',
            'CI/CD',
            'CodeBuild',
            'CodeDeploy',
            'CodePipeline',
            'CodeArtifact',
            'Git',
            'Data visualization',
            'Analytics UI development',
            'Interactive dashboards',
            'Debugging',
            'Testing',
            'unit testing',
            'integration testing',
            'maintainable test practices'
        ],
        softSkills: [
            'Collaboration',
            'Problem-solving',
            'Ownership',
            'Communication',
            'Knowledge sharing',
            'Positive engineering culture',
            'Growth mindset',
            'Innovation',
            'Teamwork'
        ]
    },
    {
        dateCreated: 1764840189000,
        companyName: '8 West Consulting',
        jobTitle: 'Front End Developer with React | (Dmitri note: 4 years plus)',
        workMode: 'Remote',
        yearsOfExperience: 4,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'React.js',
            'JavaScript',
            'DOM manipulation',
            'JavaScript object model',
            'REST API integration',
            'Rapid prototyping',
            'Accessibility (a11y)',
            'Modern testing methodologies',
            'Testing tools',
            'Testing practices',
            'Security considerations',
            'Performance optimization',
            'Cross-browser debugging',
            'JSON',
            'RESTful web services',
            'Architectural patterns',
            'Design patterns',
            'Node.js',
            'AngularJS',
            'TypeScript',
            'Relational databases',
            'Non-relational databases',
            'AWS',
            'Azure'
        ],
        softSkills: [
            'Technical leadership',
            'User feedback integration',
            'Client communication',
            'Requirements analysis',
            'Research',
            'Independent working',
            'Teamwork',
            'Stakeholder engagement',
            'Strong written communication',
            'Strong verbal communication',
            'Quick learning',
            'Continuous learning'
        ]
    },
    {
        dateCreated: 1764840344000,
        companyName: 'Stripe',
        jobTitle: 'Frontend Engineer - Remediations User Experience | (Dmitri note: 5 years plus)',
        workMode: 'Hybrid',
        yearsOfExperience: 6,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: [83200, 124800],
        hardSkills: [
            'React',
            'Angular',
            'Vue',
            'TypeScript',
            'HTML',
            'CSS',
            'Frontend performance optimization',
            'Load time optimization',
            'Custom query writing',
            'Experiment analysis',
            'End-to-end system problem solving',
            'Design and architecture collaboration'
        ],
        softSkills: [
            'Collaboration',
            'Cross-team communication',
            'Autonomy',
            'Ownership',
            'Entrepreneurial mindset',
            'User experience mindset',
            'Problem solving',
            'Working in high-growth environments'
        ]
    },
    {
        dateCreated: 1764840447000,
        companyName: 'Gong',
        jobTitle: 'Frontend Engineer | (Dmitri note: 5 years plus)',
        workMode: 'Hybrid',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'JavaScript',
            'React',
            'Frontend architecture',
            'Design systems',
            'Component architecture',
            'Building scalable web applications',
            'Cloud-based application development',
            'Node.js',
            'Java',
            'C#',
            'SaaS application development',
            'Wireframing collaboration',
            'Feature ownership',
            'Large-scale system design'
        ],
        softSkills: [
            'Ownership',
            'Responsibility',
            'Problem solving',
            'Architecture-level thinking',
            'Collaboration',
            'UX communication',
            'Teamwork',
            'Fast learning',
            'Self-motivation',
            'Independent working',
            'English communication'
        ]
    },
    {
        dateCreated: 1764840700000,
        companyName: 'Phorest Software',
        jobTitle: 'Frontend Software Engineer, Consumer - Remote | (Dmitri note: 3 years plus)',
        workMode: 'Remote',
        yearsOfExperience: 3,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'Ember.js',
            'modern JS frameworks',
            'JavaScript fundamentals',
            'RESTful APIs',
            'GraphQL',
            'Tailwind CSS',
            'Node.js',
            'Unit testing',
            'Acceptance testing',
            'Frontend design systems',
            'Responsive web applications',
            'Code maintainability',
            'code reuse',
            'Clean code principles',
            'High-performance frontend development'
        ],
        softSkills: [
            'Collaboration',
            'Proactivity',
            'Problem-solving',
            'Technical leadership',
            'Coaching teammates',
            'Attention to detail',
            'Methodical work process',
            'Continuous learning',
            'Innovation',
            'Adaptability'
        ]
    },
    {
        dateCreated: 1764840815000,
        companyName: 'Ryanair Labs',
        jobTitle: 'Frontend Developer | (Dmitri note: 4 years plus)',
        workMode: 'On-site',
        yearsOfExperience: 4,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'Angular (latest version)',
            'HTML5',
            'TypeScript',
            'JavaScript',
            'AWS',
            'azure',
            'CI/CD pipelines',
            'Cross-browser compatibility',
            'Cross-device compatibility',
            'Page performance optimization',
            'Agile development practices',
            'High-volume website coding standards',
            'E-commerce website experience'
        ],
        softSkills: [
            'Adaptability/Flexibility',
            'Dependability',
            'Communication',
            'Interpersonal skills',
            'Problem-solving',
            'Analytical skills',
            'Passion for user experience',
            'Continuous improvement mindset',
            'Collaboration with stakeholders',
            'Ability to thrive in fast-paced environments'
        ]
    },
    {
        dateCreated: 1764840892000,
        companyName: 'Ideawise Group',
        jobTitle: 'Frontend Engineer | (Dmitri note: 5 years plus)',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'React',
            'Hooks',
            'Context API',
            'modern patterns',
            'Node.js',
            'TypeScript',
            'Vite',
            'Webpack',
            'CI/CD pipelines',
            'git',
            'Docker',
            'Frontend architecture',
            'Web performance optimization',
            'Core Web Vitals',
            'Testing frameworks',
            'Jest',
            'Vitest',
            'Playwright',
            'Data structures patterns',
            'Design patterns',
            'Micro-frontend architecture',
            'Next.js',
            'TailwindCSS',
            'Storybook',
            'AI-assisted development tools',
            'Static code analysis tools',
            'SonarQube',
            'Qodana'
        ],
        softSkills: [
            'Attention to detail',
            'User empathy',
            'Storytelling ability',
            'Coachability',
            'Mentorship',
            'Ownership mindset',
            'Entrepreneurial drive',
            'Collaborative spirit',
            'Influence without authority',
            'Growth mindset',
            'Impact orientation',
            'Global collaboration'
        ]
    },
    {
        dateCreated: 1764841145000,
        companyName: 'MyEdSpace',
        jobTitle: 'Frontend Software Engineer| (Dmitri note: 4 years plus)',
        workMode: 'Remote',
        yearsOfExperience: 4,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'React',
            'TypeScript',
            'Component libraries',
            'State management patterns',
            'RESTful APIs',
            'Frontend testing',
            'unit',
            'integration',
            'end-to-end',
            'CI/CD pipelines',
            'Docker-based development environments',
            'reusable components',
            'Frontend architecture',
            'Performance best practices',
            'Reliability best practices',
            'Security best practices'
        ],
        softSkills: [
            'Product mindset',
            'Usability and UX awareness',
            'Clear communication',
            'Collaborative approach',
            'Systems thinking',
            'Ownership and accountability',
            'Iterative improvement',
            'Feedback receptiveness',
            'Integrity',
            'Teamwork'
        ]
    },
    {
        dateCreated: 1765103707000,
        companyName: 'Genesys',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: 5,
        bachelorDegree: true,
        mastersDegree: false,
        compensationRange: 'Not specified',
        hardSkills: [
            'React',
            'TypeScript',
            'Modern ECMAScript',
            'Sass',
            'Testing',
            'Jest',
            'Vitest',
            'Playwright',
            'Debugging',
            'troubleshooting',
            'Performance optimisation',
            'State management',
            'Accessibility implementation',
            'accessibility testing',
            'Node.js',
            'AWS ecosystem',
            'CI/CD practices'
        ],
        softSkills: [
            'Problem-solving',
            'Analytical thinking',
            'Cross-functional collaboration',
            'Code review and technical guidance',
            'Clean coding and maintainability',
            'Ownership and accountability',
            'Communication skills'
        ]
    },
    {
        dateCreated: 1765104021000,
        companyName: 'Revolut',
        jobTitle: 'Frontend Engineer | (Dmitri note: not sure how many hours)',
        workMode: 'Hybrid',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'JavaScript',
            'ESNext',
            'TypeScript',
            'Browser APIs',
            'ReactJS',
            'React ecosystem',
            'Styled Components',
            'Webpack',
            'Code quality principles',
            'Testing techniques',
            'Responsive design',
            'Mobile-first development',
            'Prototyping',
            'Debugging',
            'Collaboration with backend',
            'Collaboration with design'
        ],
        softSkills: [
            'Communication',
            'Organisational skills',
            'Quick learning',
            'Results-driven',
            'Teamwork',
            'Working in fast-paced environment',
            'English fluency'
        ]
    },
    {
        dateCreated: 1765104380000,
        companyName: 'Impala Search',
        jobTitle: 'Senior Frontend Engineer',
        workMode: 'Remote',
        yearsOfExperience: null,
        bachelorDegree: false,
        mastersDegree: false,
        compensationRange: null,
        hardSkills: [
            'React',
            'Advanced React',
            'TypeScript',
            'JavaScript',
            'JavaScript fundamentals',
            'Browser APIs',
            'Performance optimisation',
            'Frontend architecture',
            'Loading strategy optimisation',
            'Rendering optimisation',
            'Client-side delivery optimisation',
            'GraphQL',
            'API-driven data flows',
            'Caching strategies',
            'Client caching',
            'UI component design',
            'Frontend patterns',
            'Accessibility',
            'Responsive interfaces',
            'Design implementation',
            'Tooling improvements',
            'Documentation'
        ],
        softSkills: [
            'Communication',
            'Collaboration',
            'User-centered thinking',
            'Thoughtful code reviews',
            'Working with product teams',
            'Working with design teams',
            'Working with engineering teams'
        ]
    }
] as JobEntry[];
